-- This is generate by program !!!
-- Don't change it manaully. 
-- GenerateTime: '2017-06-07 15:00:07'

return { 
    ["Chest"] = {
        --RandID: int    随机包ID
        --Item: list_int    物品
        --Weight: int    权重
        --LowerLimit: int    等级下限
        --UpperLimit: int    等级上限
        [1] = { 
            RandID = 1,
            Item = {1012, 1000, },
            Weight = 11,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [2] = { 
            RandID = 1,
            Item = {1006, 10, },
            Weight = 10,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [3] = { 
            RandID = 1,
            Item = {4033, 1, },
            Weight = 10,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [4] = { 
            RandID = 1,
            Item = {4262, 1, },
            Weight = 5,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [5] = { 
            RandID = 1,
            Item = {1012, 10000, },
            Weight = 10,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [6] = { 
            RandID = 2,
            Item = {1012, 1000, },
            Weight = 13,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [7] = { 
            RandID = 2,
            Item = {1006, 15, },
            Weight = 10,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [8] = { 
            RandID = 2,
            Item = {4033, 1, },
            Weight = 15,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [9] = { 
            RandID = 2,
            Item = {4082, 1, },
            Weight = 5,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [10] = { 
            RandID = 2,
            Item = {1012, 20000, },
            Weight = 10,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [11] = { 
            RandID = 3,
            Item = {1012, 1000, },
            Weight = 7,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [12] = { 
            RandID = 3,
            Item = {1006, 20, },
            Weight = 10,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [13] = { 
            RandID = 3,
            Item = {4033, 2, },
            Weight = 10,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [14] = { 
            RandID = 3,
            Item = {4114, 2, },
            Weight = 15,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [15] = { 
            RandID = 3,
            Item = {1012, 30000, },
            Weight = 9,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [16] = { 
            RandID = 4,
            Item = {1012, 1000, },
            Weight = 6,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [17] = { 
            RandID = 4,
            Item = {1006, 25, },
            Weight = 10,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [18] = { 
            RandID = 4,
            Item = {4112, 1, },
            Weight = 9,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [19] = { 
            RandID = 4,
            Item = {4156, 1, },
            Weight = 17,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [20] = { 
            RandID = 4,
            Item = {1012, 40000, },
            Weight = 13,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [21] = { 
            RandID = 5,
            Item = {1012, 1000, },
            Weight = 8,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [22] = { 
            RandID = 5,
            Item = {1006, 30, },
            Weight = 15,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [23] = { 
            RandID = 5,
            Item = {4112, 1, },
            Weight = 10,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [24] = { 
            RandID = 5,
            Item = {4157, 1, },
            Weight = 8,
            LowerLimit = 1,
            UpperLimit = 150,
        },
        [25] = { 
            RandID = 5,
            Item = {1012, 50000, },
            Weight = 11,
            LowerLimit = 1,
            UpperLimit = 150,
        },
    },

    ["Liveness"] = {
        --ID: int    宝箱ID
        --ConsumeLiveness: int    消耗活跃度
        --NeedLiveness: int    开启所需活跃度
        --PackageID: int    物品ID（随机包）
        [1] = { 
            ID = 1,
            ConsumeLiveness = 30,
            NeedLiveness = 0,
            PackageID = 1,
        },
        [2] = { 
            ID = 2,
            ConsumeLiveness = 40,
            NeedLiveness = 0,
            PackageID = 2,
        },
        [3] = { 
            ID = 3,
            ConsumeLiveness = 50,
            NeedLiveness = 400,
            PackageID = 3,
        },
        [4] = { 
            ID = 4,
            ConsumeLiveness = 60,
            NeedLiveness = 700,
            PackageID = 4,
        },
        [5] = { 
            ID = 5,
            ConsumeLiveness = 70,
            NeedLiveness = 1000,
            PackageID = 5,
        },
    },

    ["Calendar"] = {
        --Date: int    日期
        --Order: int    序列
        --ActivityName: string    名称
        --Time1: string    时间段1
        --Time2: string    时间段2
        [1] = { 
            Date = 1,
            Order = 1,
            ActivityName = "科举大赛",
            Time1 = "13:00-14:00",
            Time2 = "18:00-24:00",
        },
        [2] = { 
            Date = 1,
            Order = 2,
            ActivityName = "击杀敌对",
            Time1 = "15:00-15:30",
            Time2 = "",
        },
        [3] = { 
            Date = 1,
            Order = 3,
            ActivityName = "狩猎",
            Time1 = "18:00-24:00",
            Time2 = "",
        },
        [4] = { 
            Date = 1,
            Order = 4,
            ActivityName = "猜字谜",
            Time1 = "18:00-24:00",
            Time2 = "",
        },
        [5] = { 
            Date = 2,
            Order = 1,
            ActivityName = "踩花灯",
            Time1 = "13:00-14:00",
            Time2 = "18:00-24:00",
        },
        [6] = { 
            Date = 2,
            Order = 2,
            ActivityName = "放风筝",
            Time1 = "15:00-15:30",
            Time2 = "",
        },
        [7] = { 
            Date = 2,
            Order = 3,
            ActivityName = "遛狗大赛",
            Time1 = "18:00-24:00",
            Time2 = "",
        },
        [8] = { 
            Date = 2,
            Order = 4,
            ActivityName = "科举大赛",
            Time1 = "18:00-24:00",
            Time2 = "",
        },
        [9] = { 
            Date = 3,
            Order = 1,
            ActivityName = "击杀敌对",
            Time1 = "13:00-14:00",
            Time2 = "18:00-24:00",
        },
        [10] = { 
            Date = 3,
            Order = 2,
            ActivityName = "狩猎",
            Time1 = "15:00-15:30",
            Time2 = "",
        },
        [11] = { 
            Date = 3,
            Order = 3,
            ActivityName = "猜字谜",
            Time1 = "18:00-24:00",
            Time2 = "",
        },
        [12] = { 
            Date = 4,
            Order = 1,
            ActivityName = "踩花灯",
            Time1 = "13:00-14:00",
            Time2 = "18:00-24:00",
        },
        [13] = { 
            Date = 4,
            Order = 2,
            ActivityName = "放风筝",
            Time1 = "15:00-15:30",
            Time2 = "",
        },
        [14] = { 
            Date = 4,
            Order = 3,
            ActivityName = "遛狗大赛",
            Time1 = "18:00-24:00",
            Time2 = "",
        },
        [15] = { 
            Date = 4,
            Order = 4,
            ActivityName = "科举大赛",
            Time1 = "18:00-24:00",
            Time2 = "",
        },
        [16] = { 
            Date = 5,
            Order = 1,
            ActivityName = "击杀敌对",
            Time1 = "13:00-14:00",
            Time2 = "18:00-24:00",
        },
        [17] = { 
            Date = 5,
            Order = 2,
            ActivityName = "狩猎",
            Time1 = "15:00-15:30",
            Time2 = "",
        },
        [18] = { 
            Date = 6,
            Order = 1,
            ActivityName = "猜字谜",
            Time1 = "13:00-14:00",
            Time2 = "18:00-24:00",
        },
        [19] = { 
            Date = 6,
            Order = 2,
            ActivityName = "踩花灯",
            Time1 = "15:00-15:30",
            Time2 = "",
        },
        [20] = { 
            Date = 6,
            Order = 3,
            ActivityName = "放风筝",
            Time1 = "18:00-24:00",
            Time2 = "",
        },
        [21] = { 
            Date = 6,
            Order = 4,
            ActivityName = "遛狗大赛",
            Time1 = "18:00-24:00",
            Time2 = "",
        },
        [22] = { 
            Date = 7,
            Order = 1,
            ActivityName = "科举大赛",
            Time1 = "13:00-14:00",
            Time2 = "18:00-24:00",
        },
        [23] = { 
            Date = 7,
            Order = 2,
            ActivityName = "击杀敌对",
            Time1 = "15:00-15:30",
            Time2 = "",
        },
        [24] = { 
            Date = 7,
            Order = 3,
            ActivityName = "狩猎",
            Time1 = "18:00-24:00",
            Time2 = "",
        },
        [25] = { 
            Date = 7,
            Order = 4,
            ActivityName = "猜字谜",
            Time1 = "18:00-24:00",
            Time2 = "",
        },
    },

    ["Hunting"] = {
        --ID: int    列表ID
        --ScenceID: int    场景ID
        --ScenceType: int    场景类型
        --ElementID: int    元素ID
        --Position: string    刷新位置
        --Time: string    刷新间隔
        --Details: string    简介
        --Feature: string    特点
        --iconID: list_int    掉落奖励图标ID
        [1] = { 
            ID = 1,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33200,
            Position = "琅琊花谷",
            Time = "",
            Details = "祝融，是三皇五帝时夏官火正的官名，与大司马是同义词。历史上有多位著名的祝融被后世祭祀为火神灶神。（祝融）",
            Feature = "强力的回复能力、恐怖的削弱效果，寻找具备驱散以及回复能力的队友会让你轻松许多",
            iconID = {4272, 4273, 4279, 4280, },
        },
        [2] = { 
            ID = 2,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43200,
            Position = "琴枫川",
            Time = "",
            Details = "水族朝阳谷天吴的妹妹，东海雨师国国主，芳名雨师妾，善御蛮荒奇兽，号龙女，“大荒十大妖女”之首。（雨师妾）",
            Feature = "浑身剧毒，拥有超高的单体攻击，容易针对脆皮角色，惧怕金属性宠物",
            iconID = {4272, 4273, 4279, 4280, },
        },
        [3] = { 
            ID = 3,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53200,
            Position = "阪泉古战场",
            Time = "",
            Details = "古代中国神话传说中掌管不死药、罚恶、预警灾厉的长生女神（西王母）",
            Feature = "浑身剧毒，拥有超高的单体攻击，容易针对脆皮角色，惧怕金属性宠物",
            iconID = {4272, 4273, 4279, 4280, },
        },
        [4] = { 
            ID = 4,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 63200,
            Position = "迷雾云梦泽",
            Time = "",
            Details = "传说共工素来与火神祝融不合，因“水火不相容”而发生惊天动地的大战，最后以共工失败而怒触不周山。（共工）",
            Feature = "浑身剧毒，拥有超高的单体攻击，容易针对脆皮角色，惧怕金属性宠物",
            iconID = {4272, 4273, 4279, 4280, },
        },
        [5] = { 
            ID = 5,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73200,
            Position = "空桑树海",
            Time = "",
            Details = "传说由百花山谷中悟道成仙，拥有操控百花之能，后因得罪轩辕而被打入熔岩地狱，永世承受炼狱之苦（蚩尤）",
            Feature = "浑身剧毒，拥有超高的单体攻击，容易针对脆皮角色，惧怕金属性宠物",
            iconID = {4272, 4273, 4279, 4280, },
        },
        [6] = { 
            ID = 6,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33000,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [7] = { 
            ID = 7,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33002,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [8] = { 
            ID = 8,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33004,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [9] = { 
            ID = 9,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33006,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [10] = { 
            ID = 10,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33008,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [11] = { 
            ID = 11,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33010,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [12] = { 
            ID = 12,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33012,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [13] = { 
            ID = 13,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33014,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [14] = { 
            ID = 14,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33016,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [15] = { 
            ID = 15,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33018,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [16] = { 
            ID = 16,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33020,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [17] = { 
            ID = 17,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33022,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [18] = { 
            ID = 18,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33024,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [19] = { 
            ID = 19,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33026,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [20] = { 
            ID = 20,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33028,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [21] = { 
            ID = 21,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33030,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [22] = { 
            ID = 22,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33032,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [23] = { 
            ID = 23,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33034,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [24] = { 
            ID = 24,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33036,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [25] = { 
            ID = 25,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33038,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [26] = { 
            ID = 26,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33040,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [27] = { 
            ID = 27,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33042,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [28] = { 
            ID = 28,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33044,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [29] = { 
            ID = 29,
            ScenceID = 3,
            ScenceType = 1,
            ElementID = 33046,
            Position = "琅琊花谷",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [30] = { 
            ID = 30,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43000,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [31] = { 
            ID = 31,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43002,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [32] = { 
            ID = 32,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43004,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [33] = { 
            ID = 33,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43006,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [34] = { 
            ID = 34,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43008,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [35] = { 
            ID = 35,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43010,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [36] = { 
            ID = 36,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43012,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [37] = { 
            ID = 37,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43014,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [38] = { 
            ID = 38,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43016,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [39] = { 
            ID = 39,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43018,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [40] = { 
            ID = 40,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43020,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [41] = { 
            ID = 41,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43022,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [42] = { 
            ID = 42,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43024,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [43] = { 
            ID = 43,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43026,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [44] = { 
            ID = 44,
            ScenceID = 4,
            ScenceType = 1,
            ElementID = 43028,
            Position = "琴枫川",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [45] = { 
            ID = 45,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53000,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [46] = { 
            ID = 46,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53002,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [47] = { 
            ID = 47,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53004,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [48] = { 
            ID = 48,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53006,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [49] = { 
            ID = 49,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53008,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [50] = { 
            ID = 50,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53010,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [51] = { 
            ID = 51,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53012,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [52] = { 
            ID = 52,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53014,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [53] = { 
            ID = 53,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53016,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [54] = { 
            ID = 54,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53018,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [55] = { 
            ID = 55,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53020,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [56] = { 
            ID = 56,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53022,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [57] = { 
            ID = 57,
            ScenceID = 5,
            ScenceType = 1,
            ElementID = 53024,
            Position = "阪泉古战场",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [58] = { 
            ID = 58,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43000,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [59] = { 
            ID = 59,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43002,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [60] = { 
            ID = 60,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43004,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [61] = { 
            ID = 61,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43006,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [62] = { 
            ID = 62,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43008,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [63] = { 
            ID = 63,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43010,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [64] = { 
            ID = 64,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43012,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [65] = { 
            ID = 65,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43014,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [66] = { 
            ID = 66,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43016,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [67] = { 
            ID = 67,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43018,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [68] = { 
            ID = 68,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43020,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [69] = { 
            ID = 69,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43022,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [70] = { 
            ID = 70,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43024,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [71] = { 
            ID = 71,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43026,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [72] = { 
            ID = 72,
            ScenceID = 6,
            ScenceType = 1,
            ElementID = 43028,
            Position = "迷雾云梦泽",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [73] = { 
            ID = 73,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73000,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [74] = { 
            ID = 74,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73002,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [75] = { 
            ID = 75,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73004,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [76] = { 
            ID = 76,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73006,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [77] = { 
            ID = 77,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73008,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [78] = { 
            ID = 78,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73010,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [79] = { 
            ID = 79,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73012,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [80] = { 
            ID = 80,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73014,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [81] = { 
            ID = 81,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73016,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [82] = { 
            ID = 82,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73018,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [83] = { 
            ID = 83,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73020,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [84] = { 
            ID = 84,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73022,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [85] = { 
            ID = 85,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73024,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [86] = { 
            ID = 86,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73026,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [87] = { 
            ID = 87,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73028,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [88] = { 
            ID = 88,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73030,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [89] = { 
            ID = 89,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73032,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [90] = { 
            ID = 90,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73034,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [91] = { 
            ID = 91,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73036,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [92] = { 
            ID = 92,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73038,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [93] = { 
            ID = 93,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73040,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [94] = { 
            ID = 94,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73042,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [95] = { 
            ID = 95,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73044,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
        [96] = { 
            ID = 96,
            ScenceID = 7,
            ScenceType = 1,
            ElementID = 73046,
            Position = "空桑树海",
            Time = "30分-1小时",
            Details = "曾经乃是南天门守门人，由于触犯王母被贬人间",
            Feature = "血量、防御较高",
            iconID = {4036, 4277, 4278, },
        },
    },

    ["Activity"] = {
        --ID: int    活动ID
        --Name00: int    活动名称00
        --Name: string    活动名称
        --Order: int    排序
        --ActivityType: int    活动类型
        --RefreshType: int    重置类型
        --Date: list_int    活动日期
        --DateInterval1: string    活动时间段1
        --DateInterval2: string    活动时间段2
        --ActiveNum: int    活跃次数
        --ActiveReward: int    每次活跃奖励
        --TimesUpperLimit: int    任务次数上限
        --TimesLower: int    参加等级下限
        --PartakeNum: list_int    活动人数
        --PartakeNumMS: string    活动人数描述
        --Description00: int    活动描述00
        --Description: string    活动描述
        --Main: string    主要产出物品
        --icon: list_int    活动奖励图标
        --OperationType: int    操作类型
        --OperationParameter1: string    操作参数1
        --OperationParameter2: string    操作参数2
        [1001] = { 
            ID = 1001,
            Name00 = 0,
            Name = "武林争霸",
            Order = 5,
            ActivityType = 1,
            RefreshType = 1,
            Date = {-1},
            DateInterval1 = "0:00-24:00",
            DateInterval2 = "",
            ActiveNum = 3,
            ActiveReward = 10,
            TimesUpperLimit = -1,
            TimesLower = 18,
            PartakeNum = {1},
            PartakeNumMS = "单人参加",
            Description00 = 0,
            Description = "竞技场是一个提供1V1单挑的场所，快来与众多英雄一较高下吧~！",
            Main = "竞技币",
            icon = {1005},
            OperationType = 1,
            OperationParameter1 = "",
            OperationParameter2 = "",
        },
        [1002] = { 
            ID = 1002,
            Name00 = 0,
            Name = "群雄逐鹿",
            Order = 6,
            ActivityType = 3,
            RefreshType = 1,
            Date = {3, 6, },
            DateInterval1 = "12:00-13:00",
            DateInterval2 = "18:30-19:30",
            ActiveNum = 3,
            ActiveReward = 10,
            TimesUpperLimit = -1,
            TimesLower = 35,
            PartakeNum = {1},
            PartakeNumMS = "单人参加",
            Description00 = 0,
            Description = "这是一片混乱之地，但也是英雄的磨练之地，10人混战，激情一触即发，勇士你还在等神马！！",
            Main = "竞技币",
            icon = {1005},
            OperationType = 1,
            OperationParameter1 = "",
            OperationParameter2 = "",
        },
        [1003] = { 
            ID = 1003,
            Name00 = 0,
            Name = "精英BOSS",
            Order = 4,
            ActivityType = 1,
            RefreshType = 1,
            Date = {-1},
            DateInterval1 = "0:00-24:00",
            DateInterval2 = "",
            ActiveNum = 3,
            ActiveReward = 10,
            TimesUpperLimit = -1,
            TimesLower = 10,
            PartakeNum = {1, -1, },
            PartakeNumMS = "单人/组队",
            Description00 = 0,
            Description = "异兽降临，散落世界各地为祸苍生，好男儿当仗剑江湖、斩妖除魔！击杀精英BOSS还可以获得丰厚的奖励~",
            Main = "宝石",
            icon = {4036, 4277, 4278, },
            OperationType = 3,
            OperationParameter1 = "",
            OperationParameter2 = "",
        },
        [1004] = { 
            ID = 1004,
            Name00 = 0,
            Name = "组队副本",
            Order = 2,
            ActivityType = 1,
            RefreshType = 1,
            Date = {-1},
            DateInterval1 = "0:00-24:00",
            DateInterval2 = "",
            ActiveNum = 3,
            ActiveReward = 20,
            TimesUpperLimit = 5,
            TimesLower = 20,
            PartakeNum = {3, -1, },
            PartakeNumMS = "3人以上组队",
            Description00 = 0,
            Description = "3人以上组队挑战，副本内的BOSS实力强大，需要注意配合……",
            Main = "装备",
            icon = {4272, 4273, 4018, 4276, },
            OperationType = 2,
            OperationParameter1 = "1|2|11113",
            OperationParameter2 = "2|2|21113",
        },
        [1005] = { 
            ID = 1005,
            Name00 = 0,
            Name = "妖魔入侵",
            Order = 7,
            ActivityType = 4,
            RefreshType = 1,
            Date = {-1},
            DateInterval1 = "10:00-22:00",
            DateInterval2 = "",
            ActiveNum = 2,
            ActiveReward = 10,
            TimesUpperLimit = -1,
            TimesLower = 30,
            PartakeNum = {1, -1, },
            PartakeNumMS = "单人/组队",
            Description00 = 0,
            Description = "异界来袭，妖魔横行，先遣部队已经到来，少侠快去消灭潜入大陆中的妖魔吧！活动每个整点会在各大地图刷出不等波数的妖魔，需要至少2人以上组队击杀",
            Main = "道具",
            icon = {4275, 4001, 4079, },
            OperationType = 0,
            OperationParameter1 = "",
            OperationParameter2 = "",
        },
        [1006] = { 
            ID = 1006,
            Name00 = 0,
            Name = "抓宠",
            Order = 8,
            ActivityType = 4,
            RefreshType = 1,
            Date = {-1},
            DateInterval1 = "0:00-24:00",
            DateInterval2 = "",
            ActiveNum = 3,
            ActiveReward = 5,
            TimesUpperLimit = -1,
            TimesLower = 7,
            PartakeNum = {1, -1, },
            PartakeNumMS = "不限制",
            Description00 = 0,
            Description = "快到世界各地寻找属于自己的宠物吧~~野外抓捕一只宠物~",
            Main = "宠物",
            icon = {4271},
            OperationType = 0,
            OperationParameter1 = "",
            OperationParameter2 = "",
        },
        [1007] = { 
            ID = 1007,
            Name00 = 0,
            Name = "阵营对抗",
            Order = 3,
            ActivityType = 4,
            RefreshType = 1,
            Date = {-1},
            DateInterval1 = "0:00-24:00",
            DateInterval2 = "",
            ActiveNum = 3,
            ActiveReward = 5,
            TimesUpperLimit = -1,
            TimesLower = 24,
            PartakeNum = {1, -1, },
            PartakeNumMS = "不限制",
            Description00 = 0,
            Description = "战火纷飞，前线需要少侠的支援，前往野外击杀敌对玩家",
            Main = "功勋",
            icon = {1013},
            OperationType = 0,
            OperationParameter1 = "",
            OperationParameter2 = "",
        },
        [1008] = { 
            ID = 1008,
            Name00 = 0,
            Name = "历练",
            Order = 9,
            ActivityType = 4,
            RefreshType = 1,
            Date = {-1},
            DateInterval1 = "0:00-24:00",
            DateInterval2 = "",
            ActiveNum = 0,
            ActiveReward = 0,
            TimesUpperLimit = -1,
            TimesLower = 1,
            PartakeNum = {1, -1, },
            PartakeNumMS = "不限制",
            Description00 = 0,
            Description = "历练是成长的必要一环，少侠快寻找伙伴一起到野外杀怪历练吧~~",
            Main = "经验",
            icon = {1004},
            OperationType = 0,
            OperationParameter1 = "",
            OperationParameter2 = "",
        },
        [1009] = { 
            ID = 1009,
            Name00 = 0,
            Name = "奇门遁甲",
            Order = 1,
            ActivityType = 1,
            RefreshType = 1,
            Date = {-1},
            DateInterval1 = "0:00-24:00",
            DateInterval2 = "",
            ActiveNum = 16,
            ActiveReward = 3,
            TimesUpperLimit = -1,
            TimesLower = 18,
            PartakeNum = {3, -1, },
            PartakeNumMS = "3人以上组队",
            Description00 = 0,
            Description = "环副本，需要组队挑战",
            Main = "经验",
            icon = {1004},
            OperationType = 2,
            OperationParameter1 = "1|2|11501",
            OperationParameter2 = "2|2|21501",
        },
        [1010] = { 
            ID = 1010,
            Name00 = 0,
            Name = "阵营日常",
            Order = 10,
            ActivityType = 1,
            RefreshType = 1,
            Date = {-1},
            DateInterval1 = "0:00-24:00",
            DateInterval2 = "",
            ActiveNum = 20,
            ActiveReward = 1,
            TimesUpperLimit = -1,
            TimesLower = 1,
            PartakeNum = {1},
            PartakeNumMS = "单人参加",
            Description00 = 0,
            Description = "阵营日常任务",
            Main = "阵营资金",
            icon = {1017},
            OperationType = 2,
            OperationParameter1 = "3|1|33601",
            OperationParameter2 = "7|1|73601",
        },
    },

}
