-- This is generate by program !!!
-- Don't change it manaully. 
-- GenerateTime: '2017-06-15 18:53:14'

return { 
    ["system"] = {
        --ID: int    系统ID
        --name: string    名称备注
        --systemname: int    系统名称
        --level: int    开放等级
        --icon: string    图标资源
        --Description: int    问号界面描述
        --gotolink1: list_int    九黎前往链接元素
        --gotolink2: list_int    炎黄前往链接元素
        [1010] = { 
            ID = 1010,
            name = "背包",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 1135018,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1020] = { 
            ID = 1020,
            name = "任务",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1030] = { 
            ID = 1030,
            name = "聊天",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1040] = { 
            ID = 1040,
            name = "邮件",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1050] = { 
            ID = 1050,
            name = "日常活动",
            systemname = 0,
            level = 10,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1060] = { 
            ID = 1060,
            name = "充值",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1070] = { 
            ID = 1070,
            name = "榜单",
            systemname = 0,
            level = 10,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1080] = { 
            ID = 1080,
            name = "引导",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1090] = { 
            ID = 1090,
            name = "设置",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1100] = { 
            ID = 1100,
            name = "积分商店",
            systemname = 0,
            level = 30,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1110] = { 
            ID = 1110,
            name = "商城",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1120] = { 
            ID = 1120,
            name = "技能",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 1135038,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1130] = { 
            ID = 1130,
            name = "天赋",
            systemname = 0,
            level = 30,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1140] = { 
            ID = 1140,
            name = "锻造",
            systemname = 0,
            level = 8,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1150] = { 
            ID = 1150,
            name = "装备强化",
            systemname = 0,
            level = 8,
            icon = "",
            Description = 1135032,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1160] = { 
            ID = 1160,
            name = "装备洗练",
            systemname = 0,
            level = 20,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1170] = { 
            ID = 1170,
            name = "宝石",
            systemname = 0,
            level = 30,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1171] = { 
            ID = 1171,
            name = "合成",
            systemname = 0,
            level = 30,
            icon = "",
            Description = 1135033,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1180] = { 
            ID = 1180,
            name = "宠物外观",
            systemname = 0,
            level = 33,
            icon = "",
            Description = 1135035,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1190] = { 
            ID = 1190,
            name = "宠物收集",
            systemname = 0,
            level = 150,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1200] = { 
            ID = 1200,
            name = "时装",
            systemname = 0,
            level = 15,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1210] = { 
            ID = 1210,
            name = "宝印",
            systemname = 0,
            level = 7,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1211] = { 
            ID = 1211,
            name = "宝印进阶",
            systemname = 0,
            level = 7,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1220] = { 
            ID = 1220,
            name = "宠物吞噬",
            systemname = 0,
            level = 13,
            icon = "",
            Description = 1135036,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1230] = { 
            ID = 1230,
            name = "宠物融合",
            systemname = 0,
            level = 33,
            icon = "",
            Description = 1135036,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1240] = { 
            ID = 1240,
            name = "宠物技能",
            systemname = 0,
            level = 38,
            icon = "",
            Description = 1135034,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1250] = { 
            ID = 1250,
            name = "装备星级",
            systemname = 0,
            level = 28,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1260] = { 
            ID = 1260,
            name = "神器",
            systemname = 0,
            level = 150,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1270] = { 
            ID = 1270,
            name = "主线副本",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 1135023,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1271] = { 
            ID = 1271,
            name = "副本商店",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {2, 1, 11114, },
            gotolink2 = {2, 2, 21114, },
        },
        [1280] = { 
            ID = 1280,
            name = "组队副本",
            systemname = 0,
            level = 20,
            icon = "",
            Description = 1135021,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1281] = { 
            ID = 1281,
            name = "快捷组队",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1290] = { 
            ID = 1290,
            name = "机缘副本",
            systemname = 0,
            level = 100,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1300] = { 
            ID = 1300,
            name = "通天塔",
            systemname = 0,
            level = 100,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1310] = { 
            ID = 1310,
            name = "PK系统",
            systemname = 0,
            level = 150,
            icon = "",
            Description = 1135037,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1320] = { 
            ID = 1320,
            name = "跨服战场1",
            systemname = 0,
            level = 100,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1330] = { 
            ID = 1330,
            name = "跨服战场2",
            systemname = 0,
            level = 100,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1340] = { 
            ID = 1340,
            name = "跨服战场3",
            systemname = 0,
            level = 100,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1350] = { 
            ID = 1350,
            name = "竞技场",
            systemname = 0,
            level = 18,
            icon = "",
            Description = 1135022,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1351] = { 
            ID = 1351,
            name = "竞技场-混战",
            systemname = 0,
            level = 35,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1352] = { 
            ID = 1352,
            name = "竞技场商店",
            systemname = 0,
            level = 18,
            icon = "",
            Description = 0,
            gotolink1 = {2, 1, 11116, },
            gotolink2 = {2, 2, 21116, },
        },
        [1360] = { 
            ID = 1360,
            name = "好友",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1370] = { 
            ID = 1370,
            name = "情缘",
            systemname = 0,
            level = 25,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1380] = { 
            ID = 1380,
            name = "师徒",
            systemname = 0,
            level = 25,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1390] = { 
            ID = 1390,
            name = "帮会基础",
            systemname = 0,
            level = 22,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1391] = { 
            ID = 1391,
            name = "帮贡商店",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {2, 1, 11118, },
            gotolink2 = {2, 2, 21118, },
        },
        [1392] = { 
            ID = 1392,
            name = "帮会大厅",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1393] = { 
            ID = 1393,
            name = "祭坛",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1394] = { 
            ID = 1394,
            name = "金库",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1400] = { 
            ID = 1400,
            name = "帮会副本",
            systemname = 0,
            level = 100,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1410] = { 
            ID = 1410,
            name = "帮会战",
            systemname = 0,
            level = 100,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1420] = { 
            ID = 1420,
            name = "帮会红包",
            systemname = 0,
            level = 100,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1430] = { 
            ID = 1430,
            name = "帮会仓库",
            systemname = 0,
            level = 100,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1440] = { 
            ID = 1440,
            name = "打坐",
            systemname = 0,
            level = 26,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1450] = { 
            ID = 1450,
            name = "传功",
            systemname = 0,
            level = 26,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1460] = { 
            ID = 1460,
            name = "称号",
            systemname = 0,
            level = 100,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1470] = { 
            ID = 1470,
            name = "交易",
            systemname = 0,
            level = 36,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1480] = { 
            ID = 1480,
            name = "成就",
            systemname = 0,
            level = 40,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1490] = { 
            ID = 1490,
            name = "店铺",
            systemname = 0,
            level = 36,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1500] = { 
            ID = 1500,
            name = "杂货铺",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {2, 1, 11109, },
            gotolink2 = {2, 2, 21109, },
        },
        [1501] = { 
            ID = 1501,
            name = "云游商人",
            systemname = 0,
            level = 30,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1502] = { 
            ID = 1502,
            name = "黑市",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {2, 1, 11106, },
            gotolink2 = {2, 2, 21106, },
        },
        [1510] = { 
            ID = 1510,
            name = "生活技能",
            systemname = 0,
            level = 34,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1520] = { 
            ID = 1520,
            name = "首冲",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1530] = { 
            ID = 1530,
            name = "签到",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1540] = { 
            ID = 1540,
            name = "社交",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1550] = { 
            ID = 1550,
            name = "阵营",
            systemname = 0,
            level = 24,
            icon = "",
            Description = 1135020,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1551] = { 
            ID = 1551,
            name = "功勋商店",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {2, 1, 11121, },
            gotolink2 = {2, 2, 21121, },
        },
        [1552] = { 
            ID = 1552,
            name = "阵营环任务",
            systemname = 0,
            level = 20,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1560] = { 
            ID = 1560,
            name = "挑战",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1600] = { 
            ID = 1600,
            name = "基础设置",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1601] = { 
            ID = 1601,
            name = "高级设置",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1602] = { 
            ID = 1602,
            name = "帐号设置",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
        [1603] = { 
            ID = 1603,
            name = "挂机设置",
            systemname = 0,
            level = 1,
            icon = "",
            Description = 0,
            gotolink1 = {},
            gotolink2 = {},
        },
    },

}
