-- This is generate by program !!!
-- Don't change it manaully. 
-- GenerateTime: '2017-04-14 14:20:44'

return { 
    ["GemType"] = {
        --GemID: int    宝石ID
        --name: int    显示名字
        --name1: string    名字-中文
        --color: int    颜色
        --type: int    类型
        --AttriID: int    属性ID
        --Checkweight: int    混沌石鉴定权重
        --synthweight: int    合成随机权重
        --Weapon: int    武器
        --Boot: int    靴子
        --Ring: int    戒指
        --Necklace: int    项链
        --Helmet: int    头盔
        --Armor: int    铠甲
        --Belt: int    腰带
        --Legging: int    护腿
        [1] = { 
            GemID = 1,
            name = 0,
            name1 = "精钢石",
            color = 4,
            type = 1,
            AttriID = 1,
            Checkweight = 0,
            synthweight = 10,
            Weapon = 1,
            Boot = 0,
            Ring = 1,
            Necklace = 1,
            Helmet = 0,
            Armor = 0,
            Belt = 0,
            Legging = 1,
        },
        [2] = { 
            GemID = 2,
            name = 0,
            name1 = "断金石",
            color = 3,
            type = 1,
            AttriID = 3,
            Checkweight = 0,
            synthweight = 10,
            Weapon = 0,
            Boot = 1,
            Ring = 0,
            Necklace = 0,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 0,
        },
        [3] = { 
            GemID = 3,
            name = 0,
            name1 = "太阳石",
            color = 4,
            type = 1,
            AttriID = 2,
            Checkweight = 0,
            synthweight = 10,
            Weapon = 1,
            Boot = 0,
            Ring = 1,
            Necklace = 1,
            Helmet = 0,
            Armor = 0,
            Belt = 0,
            Legging = 1,
        },
        [4] = { 
            GemID = 4,
            name = 0,
            name1 = "月亮石",
            color = 3,
            type = 1,
            AttriID = 4,
            Checkweight = 0,
            synthweight = 10,
            Weapon = 0,
            Boot = 1,
            Ring = 0,
            Necklace = 0,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 0,
        },
        [5] = { 
            GemID = 5,
            name = 0,
            name1 = "玛瑙石",
            color = 4,
            type = 1,
            AttriID = 5,
            Checkweight = 0,
            synthweight = 10,
            Weapon = 0,
            Boot = 1,
            Ring = 0,
            Necklace = 0,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 0,
        },
        [6] = { 
            GemID = 6,
            name = 0,
            name1 = "妖精石",
            color = 1,
            type = 2,
            AttriID = 6,
            Checkweight = 2,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [7] = { 
            GemID = 7,
            name = 0,
            name1 = "月纹石",
            color = 2,
            type = 2,
            AttriID = 8,
            Checkweight = 2,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [8] = { 
            GemID = 8,
            name = 0,
            name1 = "日曜石",
            color = 1,
            type = 2,
            AttriID = 7,
            Checkweight = 2,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [9] = { 
            GemID = 9,
            name = 0,
            name1 = "黄水晶",
            color = 2,
            type = 2,
            AttriID = 9,
            Checkweight = 2,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [10] = { 
            GemID = 10,
            name = 0,
            name1 = "红水晶",
            color = 1,
            type = 2,
            AttriID = 10,
            Checkweight = 2,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [11] = { 
            GemID = 11,
            name = 0,
            name1 = "蓝水晶",
            color = 2,
            type = 2,
            AttriID = 11,
            Checkweight = 2,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [12] = { 
            GemID = 12,
            name = 0,
            name1 = "紫水晶",
            color = 1,
            type = 2,
            AttriID = 12,
            Checkweight = 2,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [13] = { 
            GemID = 13,
            name = 0,
            name1 = "绿水晶",
            color = 2,
            type = 2,
            AttriID = 13,
            Checkweight = 2,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [14] = { 
            GemID = 14,
            name = 0,
            name1 = "黄宝石",
            color = 5,
            type = 1,
            AttriID = 35,
            Checkweight = 0,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [15] = { 
            GemID = 15,
            name = 0,
            name1 = "红宝石",
            color = 5,
            type = 2,
            AttriID = 36,
            Checkweight = 10,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [16] = { 
            GemID = 16,
            name = 0,
            name1 = "蓝宝石",
            color = 5,
            type = 1,
            AttriID = 37,
            Checkweight = 0,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [17] = { 
            GemID = 17,
            name = 0,
            name1 = "紫宝石",
            color = 5,
            type = 2,
            AttriID = 38,
            Checkweight = 10,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [18] = { 
            GemID = 18,
            name = 0,
            name1 = "绿宝石",
            color = 5,
            type = 1,
            AttriID = 39,
            Checkweight = 0,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [19] = { 
            GemID = 19,
            name = 0,
            name1 = "光芒石",
            color = 5,
            type = 2,
            AttriID = 40,
            Checkweight = 10,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [20] = { 
            GemID = 20,
            name = 0,
            name1 = "龙晶石",
            color = 5,
            type = 1,
            AttriID = 41,
            Checkweight = 0,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
        [21] = { 
            GemID = 21,
            name = 0,
            name1 = "星耀石",
            color = 5,
            type = 2,
            AttriID = 42,
            Checkweight = 10,
            synthweight = 10,
            Weapon = 1,
            Boot = 1,
            Ring = 1,
            Necklace = 1,
            Helmet = 1,
            Armor = 1,
            Belt = 1,
            Legging = 1,
        },
    },

    ["GemShape"] = {
        --ShapeID: int    形状ID
        --Grid: int    格数
        --weight: int    权重
        --shape: int    形状
        --ShapeNum: list_int    形状数字
        [1] = { 
            ShapeID = 1,
            Grid = 1,
            weight = 10,
            shape = 1,
            ShapeNum = {1},
        },
        [2] = { 
            ShapeID = 2,
            Grid = 2,
            weight = 10,
            shape = 2,
            ShapeNum = {1, 2, },
        },
        [3] = { 
            ShapeID = 3,
            Grid = 2,
            weight = 10,
            shape = 3,
            ShapeNum = {1, 4, },
        },
        [4] = { 
            ShapeID = 4,
            Grid = 3,
            weight = 10,
            shape = 4,
            ShapeNum = {1, 2, 4, },
        },
        [5] = { 
            ShapeID = 5,
            Grid = 3,
            weight = 10,
            shape = 5,
            ShapeNum = {1, 2, 5, },
        },
        [6] = { 
            ShapeID = 6,
            Grid = 3,
            weight = 10,
            shape = 6,
            ShapeNum = {1, 4, 5, },
        },
        [7] = { 
            ShapeID = 7,
            Grid = 3,
            weight = 10,
            shape = 7,
            ShapeNum = {1, 3, 4, },
        },
        [8] = { 
            ShapeID = 8,
            Grid = 4,
            weight = 10,
            shape = 8,
            ShapeNum = {1, 2, 4, 5, },
        },
    },

    ["GemValue"] = {
        --GemID: int    宝石ID
        --Level: int    等级
        --Num: int    属性数值
        [1] = { 
            GemID = 1,
            Level = 1,
            Num = 10,
        },
        [2] = { 
            GemID = 1,
            Level = 2,
            Num = 20,
        },
        [3] = { 
            GemID = 1,
            Level = 3,
            Num = 30,
        },
        [4] = { 
            GemID = 1,
            Level = 4,
            Num = 40,
        },
        [5] = { 
            GemID = 1,
            Level = 5,
            Num = 50,
        },
        [6] = { 
            GemID = 1,
            Level = 6,
            Num = 60,
        },
        [7] = { 
            GemID = 1,
            Level = 7,
            Num = 70,
        },
        [8] = { 
            GemID = 1,
            Level = 8,
            Num = 80,
        },
        [9] = { 
            GemID = 1,
            Level = 9,
            Num = 90,
        },
        [10] = { 
            GemID = 1,
            Level = 10,
            Num = 100,
        },
        [11] = { 
            GemID = 2,
            Level = 1,
            Num = 20,
        },
        [12] = { 
            GemID = 2,
            Level = 2,
            Num = 40,
        },
        [13] = { 
            GemID = 2,
            Level = 3,
            Num = 60,
        },
        [14] = { 
            GemID = 2,
            Level = 4,
            Num = 80,
        },
        [15] = { 
            GemID = 2,
            Level = 5,
            Num = 100,
        },
        [16] = { 
            GemID = 2,
            Level = 6,
            Num = 120,
        },
        [17] = { 
            GemID = 2,
            Level = 7,
            Num = 140,
        },
        [18] = { 
            GemID = 2,
            Level = 8,
            Num = 160,
        },
        [19] = { 
            GemID = 2,
            Level = 9,
            Num = 180,
        },
        [20] = { 
            GemID = 2,
            Level = 10,
            Num = 200,
        },
        [21] = { 
            GemID = 3,
            Level = 1,
            Num = 10,
        },
        [22] = { 
            GemID = 3,
            Level = 2,
            Num = 20,
        },
        [23] = { 
            GemID = 3,
            Level = 3,
            Num = 30,
        },
        [24] = { 
            GemID = 3,
            Level = 4,
            Num = 40,
        },
        [25] = { 
            GemID = 3,
            Level = 5,
            Num = 50,
        },
        [26] = { 
            GemID = 3,
            Level = 6,
            Num = 60,
        },
        [27] = { 
            GemID = 3,
            Level = 7,
            Num = 70,
        },
        [28] = { 
            GemID = 3,
            Level = 8,
            Num = 80,
        },
        [29] = { 
            GemID = 3,
            Level = 9,
            Num = 90,
        },
        [30] = { 
            GemID = 3,
            Level = 10,
            Num = 100,
        },
        [31] = { 
            GemID = 4,
            Level = 1,
            Num = 20,
        },
        [32] = { 
            GemID = 4,
            Level = 2,
            Num = 40,
        },
        [33] = { 
            GemID = 4,
            Level = 3,
            Num = 60,
        },
        [34] = { 
            GemID = 4,
            Level = 4,
            Num = 80,
        },
        [35] = { 
            GemID = 4,
            Level = 5,
            Num = 100,
        },
        [36] = { 
            GemID = 4,
            Level = 6,
            Num = 120,
        },
        [37] = { 
            GemID = 4,
            Level = 7,
            Num = 140,
        },
        [38] = { 
            GemID = 4,
            Level = 8,
            Num = 160,
        },
        [39] = { 
            GemID = 4,
            Level = 9,
            Num = 180,
        },
        [40] = { 
            GemID = 4,
            Level = 10,
            Num = 200,
        },
        [41] = { 
            GemID = 5,
            Level = 1,
            Num = 100,
        },
        [42] = { 
            GemID = 5,
            Level = 2,
            Num = 200,
        },
        [43] = { 
            GemID = 5,
            Level = 3,
            Num = 300,
        },
        [44] = { 
            GemID = 5,
            Level = 4,
            Num = 400,
        },
        [45] = { 
            GemID = 5,
            Level = 5,
            Num = 500,
        },
        [46] = { 
            GemID = 5,
            Level = 6,
            Num = 600,
        },
        [47] = { 
            GemID = 5,
            Level = 7,
            Num = 700,
        },
        [48] = { 
            GemID = 5,
            Level = 8,
            Num = 800,
        },
        [49] = { 
            GemID = 5,
            Level = 9,
            Num = 900,
        },
        [50] = { 
            GemID = 5,
            Level = 10,
            Num = 1000,
        },
        [51] = { 
            GemID = 6,
            Level = 1,
            Num = 300,
        },
        [52] = { 
            GemID = 6,
            Level = 2,
            Num = 600,
        },
        [53] = { 
            GemID = 6,
            Level = 3,
            Num = 900,
        },
        [54] = { 
            GemID = 6,
            Level = 4,
            Num = 1200,
        },
        [55] = { 
            GemID = 6,
            Level = 5,
            Num = 1500,
        },
        [56] = { 
            GemID = 6,
            Level = 6,
            Num = 1800,
        },
        [57] = { 
            GemID = 6,
            Level = 7,
            Num = 2100,
        },
        [58] = { 
            GemID = 6,
            Level = 8,
            Num = 2400,
        },
        [59] = { 
            GemID = 6,
            Level = 9,
            Num = 2700,
        },
        [60] = { 
            GemID = 6,
            Level = 10,
            Num = 3000,
        },
        [61] = { 
            GemID = 7,
            Level = 1,
            Num = 300,
        },
        [62] = { 
            GemID = 7,
            Level = 2,
            Num = 600,
        },
        [63] = { 
            GemID = 7,
            Level = 3,
            Num = 900,
        },
        [64] = { 
            GemID = 7,
            Level = 4,
            Num = 1200,
        },
        [65] = { 
            GemID = 7,
            Level = 5,
            Num = 1500,
        },
        [66] = { 
            GemID = 7,
            Level = 6,
            Num = 1800,
        },
        [67] = { 
            GemID = 7,
            Level = 7,
            Num = 2100,
        },
        [68] = { 
            GemID = 7,
            Level = 8,
            Num = 2400,
        },
        [69] = { 
            GemID = 7,
            Level = 9,
            Num = 2700,
        },
        [70] = { 
            GemID = 7,
            Level = 10,
            Num = 3000,
        },
        [71] = { 
            GemID = 8,
            Level = 1,
            Num = 300,
        },
        [72] = { 
            GemID = 8,
            Level = 2,
            Num = 600,
        },
        [73] = { 
            GemID = 8,
            Level = 3,
            Num = 900,
        },
        [74] = { 
            GemID = 8,
            Level = 4,
            Num = 1200,
        },
        [75] = { 
            GemID = 8,
            Level = 5,
            Num = 1500,
        },
        [76] = { 
            GemID = 8,
            Level = 6,
            Num = 1800,
        },
        [77] = { 
            GemID = 8,
            Level = 7,
            Num = 2100,
        },
        [78] = { 
            GemID = 8,
            Level = 8,
            Num = 2400,
        },
        [79] = { 
            GemID = 8,
            Level = 9,
            Num = 2700,
        },
        [80] = { 
            GemID = 8,
            Level = 10,
            Num = 3000,
        },
        [81] = { 
            GemID = 9,
            Level = 1,
            Num = 300,
        },
        [82] = { 
            GemID = 9,
            Level = 2,
            Num = 600,
        },
        [83] = { 
            GemID = 9,
            Level = 3,
            Num = 900,
        },
        [84] = { 
            GemID = 9,
            Level = 4,
            Num = 1200,
        },
        [85] = { 
            GemID = 9,
            Level = 5,
            Num = 1500,
        },
        [86] = { 
            GemID = 9,
            Level = 6,
            Num = 1800,
        },
        [87] = { 
            GemID = 9,
            Level = 7,
            Num = 2100,
        },
        [88] = { 
            GemID = 9,
            Level = 8,
            Num = 2400,
        },
        [89] = { 
            GemID = 9,
            Level = 9,
            Num = 2700,
        },
        [90] = { 
            GemID = 9,
            Level = 10,
            Num = 3000,
        },
        [91] = { 
            GemID = 10,
            Level = 1,
            Num = 300,
        },
        [92] = { 
            GemID = 10,
            Level = 2,
            Num = 600,
        },
        [93] = { 
            GemID = 10,
            Level = 3,
            Num = 900,
        },
        [94] = { 
            GemID = 10,
            Level = 4,
            Num = 1200,
        },
        [95] = { 
            GemID = 10,
            Level = 5,
            Num = 1500,
        },
        [96] = { 
            GemID = 10,
            Level = 6,
            Num = 1800,
        },
        [97] = { 
            GemID = 10,
            Level = 7,
            Num = 2100,
        },
        [98] = { 
            GemID = 10,
            Level = 8,
            Num = 2400,
        },
        [99] = { 
            GemID = 10,
            Level = 9,
            Num = 2700,
        },
        [100] = { 
            GemID = 10,
            Level = 10,
            Num = 3000,
        },
        [101] = { 
            GemID = 11,
            Level = 1,
            Num = 300,
        },
        [102] = { 
            GemID = 11,
            Level = 2,
            Num = 600,
        },
        [103] = { 
            GemID = 11,
            Level = 3,
            Num = 900,
        },
        [104] = { 
            GemID = 11,
            Level = 4,
            Num = 1200,
        },
        [105] = { 
            GemID = 11,
            Level = 5,
            Num = 1500,
        },
        [106] = { 
            GemID = 11,
            Level = 6,
            Num = 1800,
        },
        [107] = { 
            GemID = 11,
            Level = 7,
            Num = 2100,
        },
        [108] = { 
            GemID = 11,
            Level = 8,
            Num = 2400,
        },
        [109] = { 
            GemID = 11,
            Level = 9,
            Num = 2700,
        },
        [110] = { 
            GemID = 11,
            Level = 10,
            Num = 3000,
        },
        [111] = { 
            GemID = 12,
            Level = 1,
            Num = 300,
        },
        [112] = { 
            GemID = 12,
            Level = 2,
            Num = 600,
        },
        [113] = { 
            GemID = 12,
            Level = 3,
            Num = 900,
        },
        [114] = { 
            GemID = 12,
            Level = 4,
            Num = 1200,
        },
        [115] = { 
            GemID = 12,
            Level = 5,
            Num = 1500,
        },
        [116] = { 
            GemID = 12,
            Level = 6,
            Num = 1800,
        },
        [117] = { 
            GemID = 12,
            Level = 7,
            Num = 2100,
        },
        [118] = { 
            GemID = 12,
            Level = 8,
            Num = 2400,
        },
        [119] = { 
            GemID = 12,
            Level = 9,
            Num = 2700,
        },
        [120] = { 
            GemID = 12,
            Level = 10,
            Num = 3000,
        },
        [121] = { 
            GemID = 13,
            Level = 1,
            Num = 300,
        },
        [122] = { 
            GemID = 13,
            Level = 2,
            Num = 600,
        },
        [123] = { 
            GemID = 13,
            Level = 3,
            Num = 900,
        },
        [124] = { 
            GemID = 13,
            Level = 4,
            Num = 1200,
        },
        [125] = { 
            GemID = 13,
            Level = 5,
            Num = 1500,
        },
        [126] = { 
            GemID = 13,
            Level = 6,
            Num = 1800,
        },
        [127] = { 
            GemID = 13,
            Level = 7,
            Num = 2100,
        },
        [128] = { 
            GemID = 13,
            Level = 8,
            Num = 2400,
        },
        [129] = { 
            GemID = 13,
            Level = 9,
            Num = 2700,
        },
        [130] = { 
            GemID = 13,
            Level = 10,
            Num = 3000,
        },
        [131] = { 
            GemID = 14,
            Level = 1,
            Num = 2,
        },
        [132] = { 
            GemID = 14,
            Level = 2,
            Num = 4,
        },
        [133] = { 
            GemID = 14,
            Level = 3,
            Num = 6,
        },
        [134] = { 
            GemID = 14,
            Level = 4,
            Num = 8,
        },
        [135] = { 
            GemID = 14,
            Level = 5,
            Num = 10,
        },
        [136] = { 
            GemID = 14,
            Level = 6,
            Num = 12,
        },
        [137] = { 
            GemID = 14,
            Level = 7,
            Num = 14,
        },
        [138] = { 
            GemID = 14,
            Level = 8,
            Num = 16,
        },
        [139] = { 
            GemID = 14,
            Level = 9,
            Num = 18,
        },
        [140] = { 
            GemID = 14,
            Level = 10,
            Num = 20,
        },
        [141] = { 
            GemID = 15,
            Level = 1,
            Num = 5,
        },
        [142] = { 
            GemID = 15,
            Level = 2,
            Num = 10,
        },
        [143] = { 
            GemID = 15,
            Level = 3,
            Num = 15,
        },
        [144] = { 
            GemID = 15,
            Level = 4,
            Num = 20,
        },
        [145] = { 
            GemID = 15,
            Level = 5,
            Num = 25,
        },
        [146] = { 
            GemID = 15,
            Level = 6,
            Num = 30,
        },
        [147] = { 
            GemID = 15,
            Level = 7,
            Num = 35,
        },
        [148] = { 
            GemID = 15,
            Level = 8,
            Num = 40,
        },
        [149] = { 
            GemID = 15,
            Level = 9,
            Num = 45,
        },
        [150] = { 
            GemID = 15,
            Level = 10,
            Num = 50,
        },
        [151] = { 
            GemID = 16,
            Level = 1,
            Num = 2,
        },
        [152] = { 
            GemID = 16,
            Level = 2,
            Num = 4,
        },
        [153] = { 
            GemID = 16,
            Level = 3,
            Num = 6,
        },
        [154] = { 
            GemID = 16,
            Level = 4,
            Num = 8,
        },
        [155] = { 
            GemID = 16,
            Level = 5,
            Num = 10,
        },
        [156] = { 
            GemID = 16,
            Level = 6,
            Num = 12,
        },
        [157] = { 
            GemID = 16,
            Level = 7,
            Num = 14,
        },
        [158] = { 
            GemID = 16,
            Level = 8,
            Num = 16,
        },
        [159] = { 
            GemID = 16,
            Level = 9,
            Num = 18,
        },
        [160] = { 
            GemID = 16,
            Level = 10,
            Num = 20,
        },
        [161] = { 
            GemID = 17,
            Level = 1,
            Num = 5,
        },
        [162] = { 
            GemID = 17,
            Level = 2,
            Num = 10,
        },
        [163] = { 
            GemID = 17,
            Level = 3,
            Num = 15,
        },
        [164] = { 
            GemID = 17,
            Level = 4,
            Num = 20,
        },
        [165] = { 
            GemID = 17,
            Level = 5,
            Num = 25,
        },
        [166] = { 
            GemID = 17,
            Level = 6,
            Num = 30,
        },
        [167] = { 
            GemID = 17,
            Level = 7,
            Num = 35,
        },
        [168] = { 
            GemID = 17,
            Level = 8,
            Num = 40,
        },
        [169] = { 
            GemID = 17,
            Level = 9,
            Num = 45,
        },
        [170] = { 
            GemID = 17,
            Level = 10,
            Num = 50,
        },
        [171] = { 
            GemID = 18,
            Level = 1,
            Num = 2,
        },
        [172] = { 
            GemID = 18,
            Level = 2,
            Num = 4,
        },
        [173] = { 
            GemID = 18,
            Level = 3,
            Num = 6,
        },
        [174] = { 
            GemID = 18,
            Level = 4,
            Num = 8,
        },
        [175] = { 
            GemID = 18,
            Level = 5,
            Num = 10,
        },
        [176] = { 
            GemID = 18,
            Level = 6,
            Num = 12,
        },
        [177] = { 
            GemID = 18,
            Level = 7,
            Num = 14,
        },
        [178] = { 
            GemID = 18,
            Level = 8,
            Num = 16,
        },
        [179] = { 
            GemID = 18,
            Level = 9,
            Num = 18,
        },
        [180] = { 
            GemID = 18,
            Level = 10,
            Num = 20,
        },
        [181] = { 
            GemID = 19,
            Level = 1,
            Num = 5,
        },
        [182] = { 
            GemID = 19,
            Level = 2,
            Num = 10,
        },
        [183] = { 
            GemID = 19,
            Level = 3,
            Num = 15,
        },
        [184] = { 
            GemID = 19,
            Level = 4,
            Num = 20,
        },
        [185] = { 
            GemID = 19,
            Level = 5,
            Num = 25,
        },
        [186] = { 
            GemID = 19,
            Level = 6,
            Num = 30,
        },
        [187] = { 
            GemID = 19,
            Level = 7,
            Num = 35,
        },
        [188] = { 
            GemID = 19,
            Level = 8,
            Num = 40,
        },
        [189] = { 
            GemID = 19,
            Level = 9,
            Num = 45,
        },
        [190] = { 
            GemID = 19,
            Level = 10,
            Num = 50,
        },
        [191] = { 
            GemID = 20,
            Level = 1,
            Num = 2,
        },
        [192] = { 
            GemID = 20,
            Level = 2,
            Num = 4,
        },
        [193] = { 
            GemID = 20,
            Level = 3,
            Num = 6,
        },
        [194] = { 
            GemID = 20,
            Level = 4,
            Num = 8,
        },
        [195] = { 
            GemID = 20,
            Level = 5,
            Num = 10,
        },
        [196] = { 
            GemID = 20,
            Level = 6,
            Num = 12,
        },
        [197] = { 
            GemID = 20,
            Level = 7,
            Num = 14,
        },
        [198] = { 
            GemID = 20,
            Level = 8,
            Num = 16,
        },
        [199] = { 
            GemID = 20,
            Level = 9,
            Num = 18,
        },
        [200] = { 
            GemID = 20,
            Level = 10,
            Num = 20,
        },
        [201] = { 
            GemID = 21,
            Level = 1,
            Num = 5,
        },
        [202] = { 
            GemID = 21,
            Level = 2,
            Num = 10,
        },
        [203] = { 
            GemID = 21,
            Level = 3,
            Num = 15,
        },
        [204] = { 
            GemID = 21,
            Level = 4,
            Num = 20,
        },
        [205] = { 
            GemID = 21,
            Level = 5,
            Num = 25,
        },
        [206] = { 
            GemID = 21,
            Level = 6,
            Num = 30,
        },
        [207] = { 
            GemID = 21,
            Level = 7,
            Num = 35,
        },
        [208] = { 
            GemID = 21,
            Level = 8,
            Num = 40,
        },
        [209] = { 
            GemID = 21,
            Level = 9,
            Num = 45,
        },
        [210] = { 
            GemID = 21,
            Level = 10,
            Num = 50,
        },
    },

    ["Machining"] = {
        --Level: int    等级
        --Grid: int    格子数
        --weight1: int    1格权重
        --weight2: int    2格权重
        --weight3: int    3格权重
        --weight4: int    4格权重
        [1] = { 
            Level = 1,
            Grid = 2,
            weight1 = 10,
            weight2 = 30,
            weight3 = 40,
            weight4 = 20,
        },
        [2] = { 
            Level = 1,
            Grid = 3,
            weight1 = 0,
            weight2 = 20,
            weight3 = 50,
            weight4 = 30,
        },
        [3] = { 
            Level = 1,
            Grid = 4,
            weight1 = 0,
            weight2 = 0,
            weight3 = 100,
            weight4 = 0,
        },
        [4] = { 
            Level = 2,
            Grid = 2,
            weight1 = 10,
            weight2 = 30,
            weight3 = 40,
            weight4 = 20,
        },
        [5] = { 
            Level = 2,
            Grid = 3,
            weight1 = 0,
            weight2 = 20,
            weight3 = 50,
            weight4 = 30,
        },
        [6] = { 
            Level = 2,
            Grid = 4,
            weight1 = 0,
            weight2 = 0,
            weight3 = 100,
            weight4 = 0,
        },
        [7] = { 
            Level = 3,
            Grid = 2,
            weight1 = 10,
            weight2 = 30,
            weight3 = 40,
            weight4 = 20,
        },
        [8] = { 
            Level = 3,
            Grid = 3,
            weight1 = 0,
            weight2 = 20,
            weight3 = 50,
            weight4 = 30,
        },
        [9] = { 
            Level = 3,
            Grid = 4,
            weight1 = 0,
            weight2 = 0,
            weight3 = 100,
            weight4 = 0,
        },
        [10] = { 
            Level = 4,
            Grid = 2,
            weight1 = 10,
            weight2 = 30,
            weight3 = 40,
            weight4 = 20,
        },
        [11] = { 
            Level = 4,
            Grid = 3,
            weight1 = 0,
            weight2 = 20,
            weight3 = 50,
            weight4 = 30,
        },
        [12] = { 
            Level = 4,
            Grid = 4,
            weight1 = 0,
            weight2 = 0,
            weight3 = 100,
            weight4 = 0,
        },
        [13] = { 
            Level = 5,
            Grid = 2,
            weight1 = 10,
            weight2 = 30,
            weight3 = 40,
            weight4 = 20,
        },
        [14] = { 
            Level = 5,
            Grid = 3,
            weight1 = 0,
            weight2 = 20,
            weight3 = 50,
            weight4 = 30,
        },
        [15] = { 
            Level = 5,
            Grid = 4,
            weight1 = 0,
            weight2 = 0,
            weight3 = 100,
            weight4 = 0,
        },
        [16] = { 
            Level = 6,
            Grid = 2,
            weight1 = 10,
            weight2 = 30,
            weight3 = 40,
            weight4 = 20,
        },
        [17] = { 
            Level = 6,
            Grid = 3,
            weight1 = 0,
            weight2 = 20,
            weight3 = 50,
            weight4 = 30,
        },
        [18] = { 
            Level = 6,
            Grid = 4,
            weight1 = 0,
            weight2 = 0,
            weight3 = 100,
            weight4 = 0,
        },
        [19] = { 
            Level = 7,
            Grid = 2,
            weight1 = 10,
            weight2 = 30,
            weight3 = 40,
            weight4 = 20,
        },
        [20] = { 
            Level = 7,
            Grid = 3,
            weight1 = 0,
            weight2 = 20,
            weight3 = 50,
            weight4 = 30,
        },
        [21] = { 
            Level = 7,
            Grid = 4,
            weight1 = 0,
            weight2 = 0,
            weight3 = 100,
            weight4 = 0,
        },
        [22] = { 
            Level = 8,
            Grid = 2,
            weight1 = 10,
            weight2 = 30,
            weight3 = 40,
            weight4 = 20,
        },
        [23] = { 
            Level = 8,
            Grid = 3,
            weight1 = 0,
            weight2 = 20,
            weight3 = 50,
            weight4 = 30,
        },
        [24] = { 
            Level = 8,
            Grid = 4,
            weight1 = 0,
            weight2 = 0,
            weight3 = 100,
            weight4 = 0,
        },
        [25] = { 
            Level = 9,
            Grid = 2,
            weight1 = 10,
            weight2 = 30,
            weight3 = 40,
            weight4 = 20,
        },
        [26] = { 
            Level = 9,
            Grid = 3,
            weight1 = 0,
            weight2 = 20,
            weight3 = 50,
            weight4 = 30,
        },
        [27] = { 
            Level = 9,
            Grid = 4,
            weight1 = 0,
            weight2 = 0,
            weight3 = 100,
            weight4 = 0,
        },
        [28] = { 
            Level = 10,
            Grid = 2,
            weight1 = 10,
            weight2 = 30,
            weight3 = 40,
            weight4 = 20,
        },
        [29] = { 
            Level = 10,
            Grid = 3,
            weight1 = 0,
            weight2 = 20,
            weight3 = 50,
            weight4 = 30,
        },
        [30] = { 
            Level = 10,
            Grid = 4,
            weight1 = 0,
            weight2 = 0,
            weight3 = 100,
            weight4 = 0,
        },
    },

    ["GemLevel"] = {
        --Level: int    宝石等级
        --weight1: int    1格权重
        --weight2: int    2格权重
        --weight3: int    3格权重
        --weight4: int    4格权重
        --TestItem: int    对应鉴定道具
        --TestCost: list_int    鉴定消耗
        --cost1: list_int    加工消耗1
        --cost2: list_int    资源消耗
        --Specialcost: list_int    特殊消耗
        [1] = { 
            Level = 1,
            weight1 = 0,
            weight2 = 40,
            weight3 = 30,
            weight4 = 30,
            TestItem = 4059,
            TestCost = {4037, 1, },
            cost1 = {4080, 1, },
            cost2 = {1012, 10000, },
            Specialcost = {4036, 1, },
        },
        [2] = { 
            Level = 2,
            weight1 = 0,
            weight2 = 25,
            weight3 = 30,
            weight4 = 45,
            TestItem = 4060,
            TestCost = {4038, 1, },
            cost1 = {4080, 2, },
            cost2 = {1012, 10000, },
            Specialcost = {4036, 1, },
        },
        [3] = { 
            Level = 3,
            weight1 = 0,
            weight2 = 10,
            weight3 = 30,
            weight4 = 60,
            TestItem = 4061,
            TestCost = {4039, 1, },
            cost1 = {4080, 3, },
            cost2 = {1012, 10000, },
            Specialcost = {4036, 1, },
        },
        [4] = { 
            Level = 4,
            weight1 = 0,
            weight2 = 10,
            weight3 = 30,
            weight4 = 60,
            TestItem = 4062,
            TestCost = {4040, 1, },
            cost1 = {4083, 1, },
            cost2 = {1012, 10000, },
            Specialcost = {4036, 1, },
        },
        [5] = { 
            Level = 5,
            weight1 = 0,
            weight2 = 10,
            weight3 = 30,
            weight4 = 60,
            TestItem = 4063,
            TestCost = {4041, 1, },
            cost1 = {4083, 2, },
            cost2 = {1012, 10000, },
            Specialcost = {4036, 1, },
        },
        [6] = { 
            Level = 6,
            weight1 = 0,
            weight2 = 10,
            weight3 = 30,
            weight4 = 60,
            TestItem = 4064,
            TestCost = {4042, 1, },
            cost1 = {4083, 3, },
            cost2 = {1012, 10000, },
            Specialcost = {4036, 1, },
        },
        [7] = { 
            Level = 7,
            weight1 = 0,
            weight2 = 10,
            weight3 = 30,
            weight4 = 60,
            TestItem = 4065,
            TestCost = {4043, 1, },
            cost1 = {4084, 1, },
            cost2 = {1012, 10000, },
            Specialcost = {4036, 1, },
        },
        [8] = { 
            Level = 8,
            weight1 = 0,
            weight2 = 10,
            weight3 = 30,
            weight4 = 60,
            TestItem = 4066,
            TestCost = {4044, 1, },
            cost1 = {4084, 2, },
            cost2 = {1012, 10000, },
            Specialcost = {4036, 1, },
        },
        [9] = { 
            Level = 9,
            weight1 = 0,
            weight2 = 10,
            weight3 = 30,
            weight4 = 60,
            TestItem = 4067,
            TestCost = {4045, 1, },
            cost1 = {4084, 3, },
            cost2 = {1012, 10000, },
            Specialcost = {4036, 1, },
        },
        [10] = { 
            Level = 10,
            weight1 = 0,
            weight2 = 10,
            weight3 = 30,
            weight4 = 60,
            TestItem = 4068,
            TestCost = {4046, 1, },
            cost1 = {4084, 4, },
            cost2 = {1012, 10000, },
            Specialcost = {4036, 1, },
        },
    },

    ["Openings"] = {
        --GemGroove: int    宝石槽
        --cost1: list_int    消耗道具1
        --cost2: list_int    消耗道具2
        [1] = { 
            GemGroove = 1,
            cost1 = {4081, 1, },
            cost2 = {},
        },
        [2] = { 
            GemGroove = 2,
            cost1 = {4081, 2, },
            cost2 = {},
        },
        [3] = { 
            GemGroove = 3,
            cost1 = {4081, 3, },
            cost2 = {},
        },
        [4] = { 
            GemGroove = 4,
            cost1 = {4081, 4, },
            cost2 = {},
        },
        [5] = { 
            GemGroove = 5,
            cost1 = {4081, 5, },
            cost2 = {},
        },
    },

}
