-- This is generate by program !!!
-- Don't change it manaully. 
-- GenerateTime: '2017-06-21 16:19:14'

return { 
    ["TalentLv"] = {
        --Lv: int    等级
        --NeedExp: int    每级对应消耗经验
        [1] = { 
            Lv = 1,
            NeedExp = 100000,
        },
        [2] = { 
            Lv = 2,
            NeedExp = 200000,
        },
        [3] = { 
            Lv = 3,
            NeedExp = 400000,
        },
        [4] = { 
            Lv = 4,
            NeedExp = 800000,
        },
        [5] = { 
            Lv = 5,
            NeedExp = 1600000,
        },
        [6] = { 
            Lv = 6,
            NeedExp = 3200000,
        },
        [7] = { 
            Lv = 7,
            NeedExp = 6400000,
        },
        [8] = { 
            Lv = 8,
            NeedExp = 12800000,
        },
        [9] = { 
            Lv = 9,
            NeedExp = 25600000,
        },
        [10] = { 
            Lv = 10,
            NeedExp = 51200000,
        },
        [11] = { 
            Lv = 11,
            NeedExp = 102400000,
        },
    },

    ["CoreTalent"] = {
        --CoreTalentID: int    核心天赋ID
        --Parameter1: int    参数1
        --Parameter2: int    参数2
        --Parameter3: int    参数3
        --Parameter4: int    参数4
        --Parameter5: int    参数5
        [1] = { 
            CoreTalentID = 11,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
        [2] = { 
            CoreTalentID = 12,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
        [3] = { 
            CoreTalentID = 13,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
        [4] = { 
            CoreTalentID = 21,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
        [5] = { 
            CoreTalentID = 22,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
        [6] = { 
            CoreTalentID = 23,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
        [7] = { 
            CoreTalentID = 31,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
        [8] = { 
            CoreTalentID = 32,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
        [9] = { 
            CoreTalentID = 33,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
        [10] = { 
            CoreTalentID = 41,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
        [11] = { 
            CoreTalentID = 42,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
        [12] = { 
            CoreTalentID = 43,
            Parameter1 = 0,
            Parameter2 = 0,
            Parameter3 = 0,
            Parameter4 = 0,
            Parameter5 = 0,
        },
    },

    ["TalentUnlock"] = {
        --TalentPage : int    天赋页
        --NeedPlayerLv: int    解锁所需人物等级
        --NeedTalentLv: int    天赋等级条件
        [1] = { 
            TalentPage  = 1,
            NeedPlayerLv = 30,
            NeedTalentLv = 0,
        },
        [2] = { 
            TalentPage  = 2,
            NeedPlayerLv = 40,
            NeedTalentLv = 1,
        },
        [3] = { 
            TalentPage  = 3,
            NeedPlayerLv = 50,
            NeedTalentLv = 3,
        },
        [4] = { 
            TalentPage  = 4,
            NeedPlayerLv = 60,
            NeedTalentLv = 5,
        },
        [5] = { 
            TalentPage  = 5,
            NeedPlayerLv = 70,
            NeedTalentLv = 7,
        },
        [6] = { 
            TalentPage  = 6,
            NeedPlayerLv = 80,
            NeedTalentLv = 9,
        },
    },

    ["Talent"] = {
        --PostionID: int    天赋槽ID
        --LogicID: int    逻辑ID
        --Name: string    天赋名字
        --GetLockLevel: int    解锁等级
        --NeedTalentLv: int    解锁所需天赋等级
        --Parameter1: string    参数1
        --Parameter2: string    参数2
        --Parameter3: string    参数3
        --Parameter4: string    参数4
        --Parameter5: string    参数5
        --Upgrade: int    升级效果
        --Icon: int    图标
        --Bewrite: int    描述
        [1] = { 
            PostionID = 1111,
            LogicID = 1,
            Name = "属性修正1",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=10",
            Parameter2 = "B|2=100",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [2] = { 
            PostionID = 1112,
            LogicID = 1,
            Name = "属性修正2",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=11",
            Parameter2 = "B|2=110",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [3] = { 
            PostionID = 1113,
            LogicID = 1,
            Name = "属性修正3",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=12",
            Parameter2 = "B|2=120",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [4] = { 
            PostionID = 1114,
            LogicID = 1,
            Name = "属性修正4",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=13",
            Parameter2 = "B|2=130",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [5] = { 
            PostionID = 1115,
            LogicID = 1,
            Name = "属性修正5",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=14",
            Parameter2 = "B|2=140",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [6] = { 
            PostionID = 1116,
            LogicID = 1,
            Name = "属性修正6",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=15",
            Parameter2 = "B|2=150",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [7] = { 
            PostionID = 1117,
            LogicID = 1,
            Name = "属性修正7",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=16",
            Parameter2 = "B|2=160",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [8] = { 
            PostionID = 1121,
            LogicID = 1,
            Name = "属性修正8",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=17",
            Parameter2 = "B|2=170",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [9] = { 
            PostionID = 1122,
            LogicID = 1,
            Name = "属性修正9",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=18",
            Parameter2 = "B|2=180",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [10] = { 
            PostionID = 1123,
            LogicID = 1,
            Name = "属性修正10",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=19",
            Parameter2 = "B|2=190",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [11] = { 
            PostionID = 1124,
            LogicID = 1,
            Name = "属性修正11",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=20",
            Parameter2 = "B|2=200",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [12] = { 
            PostionID = 1125,
            LogicID = 1,
            Name = "属性修正12",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=21",
            Parameter2 = "B|2=210",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [13] = { 
            PostionID = 1126,
            LogicID = 1,
            Name = "属性修正13",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=22",
            Parameter2 = "B|2=220",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [14] = { 
            PostionID = 1127,
            LogicID = 1,
            Name = "属性修正14",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=23",
            Parameter2 = "B|2=230",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [15] = { 
            PostionID = 1131,
            LogicID = 1,
            Name = "属性修正15",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=24",
            Parameter2 = "B|2=240",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [16] = { 
            PostionID = 1132,
            LogicID = 1,
            Name = "属性修正16",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=25",
            Parameter2 = "B|2=250",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [17] = { 
            PostionID = 1133,
            LogicID = 1,
            Name = "属性修正17",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=26",
            Parameter2 = "B|2=260",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [18] = { 
            PostionID = 1134,
            LogicID = 1,
            Name = "属性修正18",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=27",
            Parameter2 = "B|2=270",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [19] = { 
            PostionID = 1135,
            LogicID = 1,
            Name = "属性修正19",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=28",
            Parameter2 = "B|2=280",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [20] = { 
            PostionID = 1136,
            LogicID = 1,
            Name = "属性修正20",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=29",
            Parameter2 = "B|2=290",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [21] = { 
            PostionID = 1137,
            LogicID = 1,
            Name = "属性修正21",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=30",
            Parameter2 = "B|2=300",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [22] = { 
            PostionID = 1141,
            LogicID = 1,
            Name = "属性修正22",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=31",
            Parameter2 = "B|2=310",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [23] = { 
            PostionID = 1142,
            LogicID = 1,
            Name = "属性修正23",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=32",
            Parameter2 = "B|2=320",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [24] = { 
            PostionID = 1143,
            LogicID = 1,
            Name = "属性修正24",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=33",
            Parameter2 = "B|2=330",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [25] = { 
            PostionID = 1144,
            LogicID = 1,
            Name = "属性修正25",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=34",
            Parameter2 = "B|2=340",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [26] = { 
            PostionID = 1145,
            LogicID = 1,
            Name = "属性修正26",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=35",
            Parameter2 = "B|2=350",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [27] = { 
            PostionID = 1146,
            LogicID = 1,
            Name = "属性修正27",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=36",
            Parameter2 = "B|2=360",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [28] = { 
            PostionID = 1147,
            LogicID = 1,
            Name = "属性修正28",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=37",
            Parameter2 = "B|2=370",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [29] = { 
            PostionID = 1151,
            LogicID = 1,
            Name = "属性修正29",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=38",
            Parameter2 = "B|2=380",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [30] = { 
            PostionID = 1152,
            LogicID = 1,
            Name = "属性修正30",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=39",
            Parameter2 = "B|2=390",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [31] = { 
            PostionID = 1153,
            LogicID = 1,
            Name = "属性修正31",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=40",
            Parameter2 = "B|2=400",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [32] = { 
            PostionID = 1154,
            LogicID = 1,
            Name = "属性修正32",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=41",
            Parameter2 = "B|2=410",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [33] = { 
            PostionID = 1155,
            LogicID = 1,
            Name = "属性修正33",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=42",
            Parameter2 = "B|2=420",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [34] = { 
            PostionID = 1156,
            LogicID = 1,
            Name = "属性修正34",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=43",
            Parameter2 = "B|2=430",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [35] = { 
            PostionID = 1157,
            LogicID = 1,
            Name = "属性修正35",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=44",
            Parameter2 = "B|2=440",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [36] = { 
            PostionID = 1211,
            LogicID = 1,
            Name = "属性修正36",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=45",
            Parameter2 = "B|2=450",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [37] = { 
            PostionID = 1212,
            LogicID = 1,
            Name = "属性修正37",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=46",
            Parameter2 = "B|2=460",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [38] = { 
            PostionID = 1213,
            LogicID = 1,
            Name = "属性修正38",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=47",
            Parameter2 = "B|2=470",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [39] = { 
            PostionID = 1214,
            LogicID = 1,
            Name = "属性修正39",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=48",
            Parameter2 = "B|2=480",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [40] = { 
            PostionID = 1215,
            LogicID = 1,
            Name = "属性修正40",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=49",
            Parameter2 = "B|2=490",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [41] = { 
            PostionID = 1216,
            LogicID = 1,
            Name = "属性修正41",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=50",
            Parameter2 = "B|2=500",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [42] = { 
            PostionID = 1217,
            LogicID = 1,
            Name = "属性修正42",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=51",
            Parameter2 = "B|2=510",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [43] = { 
            PostionID = 1221,
            LogicID = 1,
            Name = "属性修正43",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=52",
            Parameter2 = "B|2=520",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [44] = { 
            PostionID = 1222,
            LogicID = 1,
            Name = "属性修正44",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=53",
            Parameter2 = "B|2=530",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [45] = { 
            PostionID = 1223,
            LogicID = 1,
            Name = "属性修正45",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=54",
            Parameter2 = "B|2=540",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [46] = { 
            PostionID = 1224,
            LogicID = 1,
            Name = "属性修正46",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=55",
            Parameter2 = "B|2=550",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [47] = { 
            PostionID = 1225,
            LogicID = 1,
            Name = "属性修正47",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=56",
            Parameter2 = "B|2=560",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [48] = { 
            PostionID = 1226,
            LogicID = 1,
            Name = "属性修正48",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=57",
            Parameter2 = "B|2=570",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [49] = { 
            PostionID = 1227,
            LogicID = 1,
            Name = "属性修正49",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=58",
            Parameter2 = "B|2=580",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [50] = { 
            PostionID = 1231,
            LogicID = 1,
            Name = "属性修正50",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=59",
            Parameter2 = "B|2=590",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [51] = { 
            PostionID = 1232,
            LogicID = 1,
            Name = "属性修正51",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=60",
            Parameter2 = "B|2=600",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [52] = { 
            PostionID = 1233,
            LogicID = 1,
            Name = "属性修正52",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=61",
            Parameter2 = "B|2=610",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [53] = { 
            PostionID = 1234,
            LogicID = 1,
            Name = "属性修正53",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=62",
            Parameter2 = "B|2=620",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [54] = { 
            PostionID = 1235,
            LogicID = 1,
            Name = "属性修正54",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=63",
            Parameter2 = "B|2=630",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [55] = { 
            PostionID = 1236,
            LogicID = 1,
            Name = "属性修正55",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=64",
            Parameter2 = "B|2=640",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [56] = { 
            PostionID = 1237,
            LogicID = 1,
            Name = "属性修正56",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=65",
            Parameter2 = "B|2=650",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [57] = { 
            PostionID = 1241,
            LogicID = 1,
            Name = "属性修正57",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=66",
            Parameter2 = "B|2=660",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [58] = { 
            PostionID = 1242,
            LogicID = 1,
            Name = "属性修正58",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=67",
            Parameter2 = "B|2=670",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [59] = { 
            PostionID = 1243,
            LogicID = 1,
            Name = "属性修正59",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=68",
            Parameter2 = "B|2=680",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [60] = { 
            PostionID = 1244,
            LogicID = 1,
            Name = "属性修正60",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=69",
            Parameter2 = "B|2=690",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [61] = { 
            PostionID = 1245,
            LogicID = 1,
            Name = "属性修正61",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=70",
            Parameter2 = "B|2=700",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [62] = { 
            PostionID = 1246,
            LogicID = 1,
            Name = "属性修正62",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=71",
            Parameter2 = "B|2=710",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [63] = { 
            PostionID = 1247,
            LogicID = 1,
            Name = "属性修正63",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=72",
            Parameter2 = "B|2=720",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [64] = { 
            PostionID = 1251,
            LogicID = 1,
            Name = "属性修正64",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=73",
            Parameter2 = "B|2=730",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [65] = { 
            PostionID = 1252,
            LogicID = 1,
            Name = "属性修正65",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=74",
            Parameter2 = "B|2=740",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [66] = { 
            PostionID = 1253,
            LogicID = 1,
            Name = "属性修正66",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=75",
            Parameter2 = "B|2=750",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [67] = { 
            PostionID = 1254,
            LogicID = 1,
            Name = "属性修正67",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=76",
            Parameter2 = "B|2=760",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [68] = { 
            PostionID = 1255,
            LogicID = 1,
            Name = "属性修正68",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=77",
            Parameter2 = "B|2=770",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [69] = { 
            PostionID = 1256,
            LogicID = 1,
            Name = "属性修正69",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=78",
            Parameter2 = "B|2=780",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [70] = { 
            PostionID = 1257,
            LogicID = 1,
            Name = "属性修正70",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=79",
            Parameter2 = "B|2=790",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [71] = { 
            PostionID = 1311,
            LogicID = 1,
            Name = "属性修正71",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=80",
            Parameter2 = "B|2=800",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [72] = { 
            PostionID = 1312,
            LogicID = 1,
            Name = "属性修正72",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=81",
            Parameter2 = "B|2=810",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [73] = { 
            PostionID = 1313,
            LogicID = 1,
            Name = "属性修正73",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=82",
            Parameter2 = "B|2=820",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [74] = { 
            PostionID = 1314,
            LogicID = 1,
            Name = "属性修正74",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=83",
            Parameter2 = "B|2=830",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [75] = { 
            PostionID = 1315,
            LogicID = 1,
            Name = "属性修正75",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=84",
            Parameter2 = "B|2=840",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [76] = { 
            PostionID = 1316,
            LogicID = 1,
            Name = "属性修正76",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=85",
            Parameter2 = "B|2=850",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [77] = { 
            PostionID = 1317,
            LogicID = 1,
            Name = "属性修正77",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=86",
            Parameter2 = "B|2=860",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [78] = { 
            PostionID = 1321,
            LogicID = 1,
            Name = "属性修正78",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=87",
            Parameter2 = "B|2=870",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [79] = { 
            PostionID = 1322,
            LogicID = 1,
            Name = "属性修正79",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=88",
            Parameter2 = "B|2=880",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [80] = { 
            PostionID = 1323,
            LogicID = 1,
            Name = "属性修正80",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=89",
            Parameter2 = "B|2=890",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [81] = { 
            PostionID = 1324,
            LogicID = 1,
            Name = "属性修正81",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=90",
            Parameter2 = "B|2=900",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [82] = { 
            PostionID = 1325,
            LogicID = 1,
            Name = "属性修正82",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=91",
            Parameter2 = "B|2=910",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [83] = { 
            PostionID = 1326,
            LogicID = 1,
            Name = "属性修正83",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=92",
            Parameter2 = "B|2=920",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [84] = { 
            PostionID = 1327,
            LogicID = 1,
            Name = "属性修正84",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=93",
            Parameter2 = "B|2=930",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [85] = { 
            PostionID = 1331,
            LogicID = 1,
            Name = "属性修正85",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=94",
            Parameter2 = "B|2=940",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [86] = { 
            PostionID = 1332,
            LogicID = 1,
            Name = "属性修正86",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=95",
            Parameter2 = "B|2=950",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [87] = { 
            PostionID = 1333,
            LogicID = 1,
            Name = "属性修正87",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=96",
            Parameter2 = "B|2=960",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [88] = { 
            PostionID = 1334,
            LogicID = 1,
            Name = "属性修正88",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=97",
            Parameter2 = "B|2=970",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [89] = { 
            PostionID = 1335,
            LogicID = 1,
            Name = "属性修正89",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=98",
            Parameter2 = "B|2=980",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [90] = { 
            PostionID = 1336,
            LogicID = 1,
            Name = "属性修正90",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=99",
            Parameter2 = "B|2=990",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [91] = { 
            PostionID = 1337,
            LogicID = 1,
            Name = "属性修正91",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=100",
            Parameter2 = "B|2=1000",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [92] = { 
            PostionID = 1341,
            LogicID = 1,
            Name = "属性修正92",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=101",
            Parameter2 = "B|2=1010",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [93] = { 
            PostionID = 1342,
            LogicID = 1,
            Name = "属性修正93",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=102",
            Parameter2 = "B|2=1020",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [94] = { 
            PostionID = 1343,
            LogicID = 1,
            Name = "属性修正94",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=103",
            Parameter2 = "B|2=1030",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [95] = { 
            PostionID = 1344,
            LogicID = 1,
            Name = "属性修正95",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=104",
            Parameter2 = "B|2=1040",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [96] = { 
            PostionID = 1345,
            LogicID = 1,
            Name = "属性修正96",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=105",
            Parameter2 = "B|2=1050",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [97] = { 
            PostionID = 1346,
            LogicID = 1,
            Name = "属性修正97",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=106",
            Parameter2 = "B|2=1060",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [98] = { 
            PostionID = 1347,
            LogicID = 1,
            Name = "属性修正98",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=107",
            Parameter2 = "B|2=1070",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [99] = { 
            PostionID = 1351,
            LogicID = 1,
            Name = "属性修正99",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=108",
            Parameter2 = "B|2=1080",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [100] = { 
            PostionID = 1352,
            LogicID = 1,
            Name = "属性修正100",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=109",
            Parameter2 = "B|2=1090",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [101] = { 
            PostionID = 1353,
            LogicID = 1,
            Name = "属性修正101",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=110",
            Parameter2 = "B|2=1100",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [102] = { 
            PostionID = 1354,
            LogicID = 1,
            Name = "属性修正102",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=111",
            Parameter2 = "B|2=1110",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [103] = { 
            PostionID = 1355,
            LogicID = 1,
            Name = "属性修正103",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=112",
            Parameter2 = "B|2=1120",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [104] = { 
            PostionID = 1356,
            LogicID = 1,
            Name = "属性修正104",
            GetLockLevel = 10,
            NeedTalentLv = 0,
            Parameter1 = "A|1=113",
            Parameter2 = "B|2=1130",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
        [105] = { 
            PostionID = 1357,
            LogicID = 1,
            Name = "属性修正105",
            GetLockLevel = 0,
            NeedTalentLv = 30,
            Parameter1 = "A|1=114",
            Parameter2 = "B|2=1140",
            Parameter3 = "",
            Parameter4 = "",
            Parameter5 = "",
            Upgrade = 0,
            Icon = 0,
            Bewrite = 0,
        },
    },

    ["TalentUpgrade"] = {
        --TalentSlotID: int    天赋槽ID
        --Lv_lower: int    等级下限
        --Consume1ID: list_int    消耗1ID
        --Consume2ID: list_int    消耗2ID
        --ConsumeIncrement1: int    消耗1增量
        --ConsumeIncrement2: int    消耗2增量
        [1] = { 
            TalentSlotID = 1111,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [2] = { 
            TalentSlotID = 1111,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [3] = { 
            TalentSlotID = 1112,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [4] = { 
            TalentSlotID = 1112,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [5] = { 
            TalentSlotID = 1113,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [6] = { 
            TalentSlotID = 1113,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [7] = { 
            TalentSlotID = 1114,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [8] = { 
            TalentSlotID = 1114,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [9] = { 
            TalentSlotID = 1115,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [10] = { 
            TalentSlotID = 1115,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [11] = { 
            TalentSlotID = 1116,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [12] = { 
            TalentSlotID = 1116,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [13] = { 
            TalentSlotID = 1117,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [14] = { 
            TalentSlotID = 1117,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [15] = { 
            TalentSlotID = 1121,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [16] = { 
            TalentSlotID = 1121,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [17] = { 
            TalentSlotID = 1122,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [18] = { 
            TalentSlotID = 1122,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [19] = { 
            TalentSlotID = 1123,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [20] = { 
            TalentSlotID = 1123,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [21] = { 
            TalentSlotID = 1124,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [22] = { 
            TalentSlotID = 1124,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [23] = { 
            TalentSlotID = 1125,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [24] = { 
            TalentSlotID = 1125,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [25] = { 
            TalentSlotID = 1126,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [26] = { 
            TalentSlotID = 1126,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [27] = { 
            TalentSlotID = 1127,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [28] = { 
            TalentSlotID = 1127,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [29] = { 
            TalentSlotID = 1131,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [30] = { 
            TalentSlotID = 1131,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [31] = { 
            TalentSlotID = 1132,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [32] = { 
            TalentSlotID = 1132,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [33] = { 
            TalentSlotID = 1133,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [34] = { 
            TalentSlotID = 1133,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [35] = { 
            TalentSlotID = 1134,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [36] = { 
            TalentSlotID = 1134,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [37] = { 
            TalentSlotID = 1135,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [38] = { 
            TalentSlotID = 1135,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [39] = { 
            TalentSlotID = 1136,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [40] = { 
            TalentSlotID = 1136,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [41] = { 
            TalentSlotID = 1137,
            Lv_lower = 0,
            Consume1ID = {1012, 2000, },
            Consume2ID = {1004, 4000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [42] = { 
            TalentSlotID = 1137,
            Lv_lower = 100,
            Consume1ID = {1012, 200000, },
            Consume2ID = {1004, 400000, },
            ConsumeIncrement1 = 200,
            ConsumeIncrement2 = 4000,
        },
        [43] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [44] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [45] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [46] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [47] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [48] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [49] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [50] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [51] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [52] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [53] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [54] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [55] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [56] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [57] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [58] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [59] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [60] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [61] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [62] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [63] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [64] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [65] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [66] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [67] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [68] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [69] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [70] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [71] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [72] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [73] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [74] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [75] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [76] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [77] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [78] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [79] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [80] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [81] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [82] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [83] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [84] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [85] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [86] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [87] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [88] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [89] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [90] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [91] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [92] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [93] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [94] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [95] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [96] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [97] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [98] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [99] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [100] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
        [101] = { 
            TalentSlotID = 0,
            Lv_lower = 0,
            Consume1ID = {},
            Consume2ID = {},
            ConsumeIncrement1 = 0,
            ConsumeIncrement2 = 0,
        },
    },

}
