-- This is generate by program !!!
-- Don't change it manaully. 
-- GenerateTime: '2017-06-23 15:48:26'

return { 
    ["Task"] = {
        --ID: int    ID
        --TaskNum: int    任务序号
        --Camp: int    阵营限制
        --mark: int    系统刷新固定标志
        --LogicID: int    任务逻辑ID
        --description: string    阵营任务描述
        --para1: int    参数1
        --para2: int    参数2
        --para3: int    参数3
        --Reward1: list_int    奖励1
        --Reward2: list_int    奖励2
        --Reward3: list_int    奖励3
        --Reward4: list_int    奖励4
        --Star: int    星级
        [1] = { 
            ID = 1,
            TaskNum = 1,
            Camp = 0,
            mark = 1,
            LogicID = 1,
            description = "获得攻防战胜利",
            para1 = 0,
            para2 = 0,
            para3 = 0,
            Reward1 = {1001, 10000, },
            Reward2 = {1515, 5, },
            Reward3 = {},
            Reward4 = {},
            Star = 5,
        },
        [2] = { 
            ID = 2,
            TaskNum = 1,
            Camp = 0,
            mark = 0,
            LogicID = 3,
            description = "攻防战积分达到20",
            para1 = 20,
            para2 = 0,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 4,
        },
        [3] = { 
            ID = 3,
            TaskNum = 1,
            Camp = 0,
            mark = 0,
            LogicID = 3,
            description = "攻防战积分达到15",
            para1 = 10,
            para2 = 0,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 3,
        },
        [4] = { 
            ID = 4,
            TaskNum = 2,
            Camp = 1,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-轩辕",
            para1 = 7,
            para2 = 73601,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 2,
        },
        [5] = { 
            ID = 5,
            TaskNum = 2,
            Camp = 1,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-后羿",
            para1 = 7,
            para2 = 73605,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 1,
        },
        [6] = { 
            ID = 6,
            TaskNum = 2,
            Camp = 1,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-嫦娥",
            para1 = 7,
            para2 = 73609,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 1,
        },
        [7] = { 
            ID = 7,
            TaskNum = 2,
            Camp = 1,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-仓颉",
            para1 = 7,
            para2 = 73619,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 1,
        },
        [8] = { 
            ID = 8,
            TaskNum = 2,
            Camp = 1,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-瑶姬",
            para1 = 6,
            para2 = 63601,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 1,
        },
        [9] = { 
            ID = 9,
            TaskNum = 2,
            Camp = 1,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-力牧",
            para1 = 5,
            para2 = 53604,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 1,
        },
        [10] = { 
            ID = 10,
            TaskNum = 2,
            Camp = 2,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-祝融",
            para1 = 5,
            para2 = 53601,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 1,
        },
        [11] = { 
            ID = 11,
            TaskNum = 2,
            Camp = 2,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-刑天",
            para1 = 4,
            para2 = 43601,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 1,
        },
        [12] = { 
            ID = 12,
            TaskNum = 2,
            Camp = 2,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-蚩尤",
            para1 = 3,
            para2 = 33601,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 1,
        },
        [13] = { 
            ID = 13,
            TaskNum = 2,
            Camp = 2,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-雨师妾",
            para1 = 3,
            para2 = 33605,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 1,
        },
        [14] = { 
            ID = 14,
            TaskNum = 2,
            Camp = 2,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-银灵子",
            para1 = 3,
            para2 = 33609,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 2,
        },
        [15] = { 
            ID = 15,
            TaskNum = 2,
            Camp = 2,
            mark = 0,
            LogicID = 2,
            description = "参与击杀敌方阵营boss-共工",
            para1 = 3,
            para2 = 33619,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 1,
        },
        [16] = { 
            ID = 16,
            TaskNum = 3,
            Camp = 0,
            mark = 0,
            LogicID = 4,
            description = "战功达到20",
            para1 = 20,
            para2 = 0,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 2,
        },
        [17] = { 
            ID = 17,
            TaskNum = 3,
            Camp = 0,
            mark = 0,
            LogicID = 6,
            description = "提交箭矢数量达到100",
            para1 = 100,
            para2 = 0,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 3,
        },
        [18] = { 
            ID = 18,
            TaskNum = 3,
            Camp = 0,
            mark = 0,
            LogicID = 5,
            description = "摧毁3辆物资车",
            para1 = 3,
            para2 = 0,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 4,
        },
        [19] = { 
            ID = 19,
            TaskNum = 3,
            Camp = 0,
            mark = 0,
            LogicID = 7,
            description = "恢复1次boss血量",
            para1 = 1,
            para2 = 0,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 5,
        },
        [20] = { 
            ID = 20,
            TaskNum = 3,
            Camp = 0,
            mark = 0,
            LogicID = 0,
            description = "恢复3次boss血量",
            para1 = 3,
            para2 = 0,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 0,
        },
        [21] = { 
            ID = 21,
            TaskNum = 3,
            Camp = 0,
            mark = 0,
            LogicID = 0,
            description = "恢复5次boss血量",
            para1 = 5,
            para2 = 0,
            para3 = 0,
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Star = 0,
        },
    },

    ["ScoreReward"] = {
        --Type: int    行为
        --Goal: list_int    目标
        --CampScore: int    阵营积分
        --BattleScore: int    战功
        --Reward1: list_int    奖励1
        --Reward2: list_int    奖励2
        [1] = { 
            Type = 1,
            Goal = {23, 10, },
            CampScore = 100,
            BattleScore = 100,
            Reward1 = {},
            Reward2 = {},
        },
        [2] = { 
            Type = 1,
            Goal = {23, 5, },
            CampScore = 15,
            BattleScore = 15,
            Reward1 = {},
            Reward2 = {},
        },
        [3] = { 
            Type = 1,
            Goal = {23, 8, },
            CampScore = 4,
            BattleScore = 4,
            Reward1 = {},
            Reward2 = {},
        },
        [4] = { 
            Type = 1,
            Goal = {23, 9, },
            CampScore = 2,
            BattleScore = 2,
            Reward1 = {},
            Reward2 = {},
        },
        [5] = { 
            Type = 1,
            Goal = {1},
            CampScore = 0,
            BattleScore = 1,
            Reward1 = {},
            Reward2 = {},
        },
        [6] = { 
            Type = 1,
            Goal = {2},
            CampScore = 1,
            BattleScore = 1,
            Reward1 = {},
            Reward2 = {},
        },
        [7] = { 
            Type = 2,
            Goal = {23, 10, },
            CampScore = 0,
            BattleScore = 10,
            Reward1 = {},
            Reward2 = {},
        },
        [8] = { 
            Type = 2,
            Goal = {23, 5, },
            CampScore = 0,
            BattleScore = 5,
            Reward1 = {},
            Reward2 = {},
        },
        [9] = { 
            Type = 2,
            Goal = {23, 8, },
            CampScore = 0,
            BattleScore = 2,
            Reward1 = {},
            Reward2 = {},
        },
        [10] = { 
            Type = 2,
            Goal = {23, 9, },
            CampScore = 0,
            BattleScore = 1,
            Reward1 = {},
            Reward2 = {},
        },
        [11] = { 
            Type = 2,
            Goal = {1},
            CampScore = 0,
            BattleScore = 1,
            Reward1 = {},
            Reward2 = {},
        },
        [12] = { 
            Type = 2,
            Goal = {2},
            CampScore = 0,
            BattleScore = 1,
            Reward1 = {},
            Reward2 = {},
        },
        [13] = { 
            Type = 3,
            Goal = {},
            CampScore = 10,
            BattleScore = 10,
            Reward1 = {},
            Reward2 = {},
        },
    },

    ["NpcLevel"] = {
        --Type: int    怪物类型
        --level: int    修正等级
        [1] = { 
            Type = 5,
            level = 10,
        },
        [2] = { 
            Type = 8,
            level = 5,
        },
        [3] = { 
            Type = 9,
            level = 3,
        },
        [4] = { 
            Type = 10,
            level = 15,
        },
    },

    ["TaskRefresh"] = {
        --Number: int    次数下限
        --Cost: list_int    消耗
        [1] = { 
            Number = 1,
            Cost = {1012, 1000, },
        },
        [2] = { 
            Number = 3,
            Cost = {1012, 3000, },
        },
        [3] = { 
            Number = 5,
            Cost = {1012, 5000, },
        },
        [4] = { 
            Number = 10,
            Cost = {1012, 10000, },
        },
    },

    ["MilExploits"] = {
        --MilExploits: int    战功
        --Reward1: list_int    奖励1
        --Reward2: list_int    奖励2
        --Reward3: list_int    奖励3
        --Reward4: list_int    奖励4
        --Reward5: list_int    奖励5
        [1] = { 
            MilExploits = 100,
            Reward1 = {1012, 1000, },
            Reward2 = {1012, 1000, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [2] = { 
            MilExploits = 500,
            Reward1 = {1011, 100, },
            Reward2 = {1011, 100, },
            Reward3 = {1012, 1000, },
            Reward4 = {1012, 1000, },
            Reward5 = {},
        },
        [3] = { 
            MilExploits = 1000,
            Reward1 = {1011, 100, },
            Reward2 = {1011, 100, },
            Reward3 = {1012, 1000, },
            Reward4 = {1012, 1000, },
            Reward5 = {1012, 1000, },
        },
    },

    ["RankingReward"] = {
        --RankedLowerlimit: int    排名下限
        --Reward1: list_int    奖励1
        --Reward2: list_int    奖励2
        --Reward3: list_int    奖励3
        --Reward4: list_int    奖励4
        [1] = { 
            RankedLowerlimit = 1,
            Reward1 = {1006, 1000, },
            Reward2 = {1008, 2000, },
            Reward3 = {4204, 1, },
            Reward4 = {4025, 10, },
        },
        [2] = { 
            RankedLowerlimit = 10,
            Reward1 = {1006, 1000, },
            Reward2 = {1008, 1900, },
            Reward3 = {4160, 1, },
            Reward4 = {4025, 10, },
        },
        [3] = { 
            RankedLowerlimit = 50,
            Reward1 = {1006, 1000, },
            Reward2 = {1008, 1800, },
            Reward3 = {4159, 1, },
            Reward4 = {4025, 10, },
        },
        [4] = { 
            RankedLowerlimit = 100,
            Reward1 = {1006, 20, },
            Reward2 = {1008, 100, },
            Reward3 = {},
            Reward4 = {},
        },
        [5] = { 
            RankedLowerlimit = 9999,
            Reward1 = {1006, 20, },
            Reward2 = {1008, 80, },
            Reward3 = {},
            Reward4 = {},
        },
    },

    ["CampNpcTask"] = {
        --ID: int    ID
        --MapID: int    地图ID
        --ElementID: int    场景元素
        --TaskType: int    任务类型
        --TaskName: int    任务名称
        --TaskName1: string    任务名称
        --TaskDialogue: string    接取npc对话
        --UncommittedDialogue: string    没有道具npc对话
        --CompleteDialogue: string    完成npc对话
        --ItemMax: list_int    回收道具数量上限
        --Item: list_int    回收道具
        --Recovery: int    恢复血量
        --Reward1: list_int    奖励1
        --Reward2: list_int    奖励2
        --Reward3: list_int    奖励3
        [1] = { 
            ID = 1,
            MapID = 3,
            ElementID = 33601,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "蚩尤:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "蚩尤:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "蚩尤:年轻人，我看好你。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [2] = { 
            ID = 2,
            MapID = 3,
            ElementID = 33605,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "雨师妾:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "雨师妾:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "雨师妾:积少成多。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [3] = { 
            ID = 3,
            MapID = 3,
            ElementID = 33609,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "银灵子:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "银灵子:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "银灵子:积少成多。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [4] = { 
            ID = 4,
            MapID = 3,
            ElementID = 33619,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "共工:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "共工:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "共工:积少成多。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [5] = { 
            ID = 5,
            MapID = 4,
            ElementID = 43601,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "刑天:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "刑天:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "刑天:积少成多。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [6] = { 
            ID = 6,
            MapID = 5,
            ElementID = 53601,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "祝融:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "祝融:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "祝融:积少成多。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [7] = { 
            ID = 7,
            MapID = 5,
            ElementID = 53604,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "力牧:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "力牧:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "力牧:积少成多。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [8] = { 
            ID = 8,
            MapID = 6,
            ElementID = 63601,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "瑶姬:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "瑶姬:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "瑶姬:积少成多。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [9] = { 
            ID = 9,
            MapID = 7,
            ElementID = 73601,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "轩辕:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "轩辕:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "轩辕:年轻人，我看好你。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [10] = { 
            ID = 10,
            MapID = 7,
            ElementID = 73605,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "后羿:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "后羿:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "后羿:积少成多。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [11] = { 
            ID = 11,
            MapID = 7,
            ElementID = 73609,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "嫦娥:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "嫦娥:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "嫦娥:积少成多。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [12] = { 
            ID = 12,
            MapID = 7,
            ElementID = 73619,
            TaskType = 1,
            TaskName = 0,
            TaskName1 = "恢复",
            TaskDialogue = "仓颉:给我收集凤泣血露，我就能恢复血量。可获得100阵营资金，10点功勋",
            UncommittedDialogue = "仓颉:别忽悠我，哪来的凤泣血露。",
            CompleteDialogue = "仓颉:积少成多。",
            ItemMax = {},
            Item = {1515, 1, },
            Recovery = 5,
            Reward1 = {1017, 100, },
            Reward2 = {1013, 10, },
            Reward3 = {},
        },
        [13] = { 
            ID = 13,
            MapID = 3,
            ElementID = 33602,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [14] = { 
            ID = 14,
            MapID = 3,
            ElementID = 33604,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [15] = { 
            ID = 15,
            MapID = 3,
            ElementID = 33608,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [16] = { 
            ID = 16,
            MapID = 3,
            ElementID = 33615,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [17] = { 
            ID = 17,
            MapID = 3,
            ElementID = 33618,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [18] = { 
            ID = 18,
            MapID = 4,
            ElementID = 43602,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [19] = { 
            ID = 19,
            MapID = 4,
            ElementID = 43603,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [20] = { 
            ID = 20,
            MapID = 5,
            ElementID = 53602,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [21] = { 
            ID = 21,
            MapID = 5,
            ElementID = 53603,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [22] = { 
            ID = 22,
            MapID = 5,
            ElementID = 53605,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [23] = { 
            ID = 23,
            MapID = 5,
            ElementID = 53606,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [24] = { 
            ID = 24,
            MapID = 6,
            ElementID = 63602,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [25] = { 
            ID = 25,
            MapID = 6,
            ElementID = 63603,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [26] = { 
            ID = 26,
            MapID = 7,
            ElementID = 73602,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [27] = { 
            ID = 27,
            MapID = 7,
            ElementID = 73604,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [28] = { 
            ID = 28,
            MapID = 7,
            ElementID = 73608,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [29] = { 
            ID = 29,
            MapID = 7,
            ElementID = 73615,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
        [30] = { 
            ID = 30,
            MapID = 7,
            ElementID = 73618,
            TaskType = 2,
            TaskName = 0,
            TaskName1 = "补给",
            TaskDialogue = "箭塔:找来100支箭矢，我就能恢复血量。可得到10阵营资金。",
            UncommittedDialogue = "箭塔:你的箭矢不足，快去收集吧。",
            CompleteDialogue = "箭塔:众志成城！",
            ItemMax = {1014, 100000, },
            Item = {1514, 100, },
            Recovery = 1,
            Reward1 = {1017, 10, },
            Reward2 = {},
            Reward3 = {},
        },
    },

    ["BossBuff"] = {
        --LostNumLimit: int    连输次数下限
        --buffID: int    buffID
        [1] = { 
            LostNumLimit = 1,
            buffID = 502,
        },
        [2] = { 
            LostNumLimit = 3,
            buffID = 503,
        },
        [3] = { 
            LostNumLimit = 5,
            buffID = 504,
        },
    },

    ["Parameter"] = {
        --ID: int    参数ID
        --Value: list_int    值
        [1] = { 
            ID = 1,
            Value = {3},
        },
        [2] = { 
            ID = 2,
            Value = {60},
        },
        [3] = { 
            ID = 3,
            Value = {30},
        },
        [4] = { 
            ID = 4,
            Value = {1, 2, 3, 4, 5, 6, 7, },
        },
        [5] = { 
            ID = 5,
            Value = {9, 0, 20, 30, },
        },
        [6] = { 
            ID = 6,
            Value = {8, 0, },
        },
        [7] = { 
            ID = 7,
            Value = {3},
        },
        [8] = { 
            ID = 8,
            Value = {10, 30, 10, 45, 11, 0, 11, 15, 12, 0, 19, 10, 19, 15, },
        },
        [9] = { 
            ID = 9,
            Value = {2},
        },
        [10] = { 
            ID = 10,
            Value = {9042},
        },
        [11] = { 
            ID = 11,
            Value = {802},
        },
        [12] = { 
            ID = 12,
            Value = {300},
        },
        [13] = { 
            ID = 13,
            Value = {5},
        },
    },

}
