-- This is generate by program !!!
-- Don't change it manaully. 
-- GenerateTime: '2017-06-21 11:01:30'

return { 
    ["ElectionDuration"] = {
        --ID: int    ID
        --name: string    事项
        --begindate: int    开始日期
        --begintime: list_int    开始时间
        --enddate: int    结束日期
        --endtime: list_int    结束时间
        [1] = { 
            ID = 1,
            name = "资格判定",
            begindate = 4,
            begintime = {16, 0, },
            enddate = 4,
            endtime = {16, 0, },
        },
        [2] = { 
            ID = 2,
            name = "提名",
            begindate = 4,
            begintime = {16, 0, },
            enddate = 4,
            endtime = {16, 15, },
        },
        [3] = { 
            ID = 3,
            name = "选举",
            begindate = 4,
            begintime = {16, 15, },
            enddate = 4,
            endtime = {16, 30, },
        },
        [4] = { 
            ID = 4,
            name = "结算",
            begindate = 4,
            begintime = {16, 30, },
            enddate = 4,
            endtime = {16, 30, },
        },
    },

    ["OfficerSkill"] = {
        --ID: int    ID
        --skillname: string    技能名称
        --CD: int    CD时间
        --Cdprice: int    重置价格
        --parameter1: int    参数1
        --parameter2: int    参数2
        --parameter3: int    参数3
        [1] = { 
            ID = 1,
            skillname = "阵营召集",
            CD = 180,
            Cdprice = 120,
            parameter1 = 120,
            parameter2 = 10,
            parameter3 = 1,
        },
        [2] = { 
            ID = 2,
            skillname = "开启阵营任务",
            CD = 0,
            Cdprice = 120,
            parameter1 = 0,
            parameter2 = 0,
            parameter3 = 0,
        },
        [3] = { 
            ID = 3,
            skillname = "开启阵营设施状态",
            CD = 180,
            Cdprice = 120,
            parameter1 = 0,
            parameter2 = 0,
            parameter3 = 0,
        },
        [4] = { 
            ID = 4,
            skillname = "开启BOSS状态",
            CD = 180,
            Cdprice = 120,
            parameter1 = 0,
            parameter2 = 0,
            parameter3 = 0,
        },
        [5] = { 
            ID = 5,
            skillname = "阵营全体BUFF",
            CD = 720,
            Cdprice = 120,
            parameter1 = 0,
            parameter2 = 0,
            parameter3 = 0,
        },
        [6] = { 
            ID = 6,
            skillname = "光环技能",
            CD = 0,
            Cdprice = 120,
            parameter1 = 0,
            parameter2 = 0,
            parameter3 = 0,
        },
        [7] = { 
            ID = 7,
            skillname = "阵营调兵",
            CD = 0,
            Cdprice = 120,
            parameter1 = 0,
            parameter2 = 0,
            parameter3 = 0,
        },
        [8] = { 
            ID = 8,
            skillname = "打折功能",
            CD = 720,
            Cdprice = 120,
            parameter1 = 0,
            parameter2 = 0,
            parameter3 = 0,
        },
        [9] = { 
            ID = 9,
            skillname = "开关传送阵",
            CD = 0,
            Cdprice = 120,
            parameter1 = 0,
            parameter2 = 0,
            parameter3 = 0,
        },
        [10] = { 
            ID = 10,
            skillname = "发放俸禄",
            CD = 0,
            Cdprice = 120,
            parameter1 = 0,
            parameter2 = 0,
            parameter3 = 0,
        },
    },

    ["PlunderPrestige"] = {
        --Deathlowerlimit: int    被杀次数下限
        --Plunderuplimit: int    被掠夺比例上限
        --Plunderlowlimit: int    被掠夺比例下限
        [1] = { 
            Deathlowerlimit = 1,
            Plunderuplimit = 500,
            Plunderlowlimit = 200,
        },
        [2] = { 
            Deathlowerlimit = 4,
            Plunderuplimit = 300,
            Plunderlowlimit = 150,
        },
        [3] = { 
            Deathlowerlimit = 7,
            Plunderuplimit = 150,
            Plunderlowlimit = 50,
        },
        [4] = { 
            Deathlowerlimit = 10,
            Plunderuplimit = 30,
            Plunderlowlimit = 10,
        },
        [5] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [6] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [7] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [8] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [9] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [10] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [11] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [12] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [13] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [14] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [15] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [16] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [17] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [18] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [19] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [20] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [21] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [22] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [23] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [24] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [25] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [26] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [27] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
        [28] = { 
            Deathlowerlimit = 0,
            Plunderuplimit = 0,
            Plunderlowlimit = 0,
        },
    },

    ["Rank"] = {
        --ID: int    战阶ID
        --Lv: int    升阶等级要求
        --Name: int    战阶名称
        --Name1: string    战阶名称-策划用
        --RequirePrestige: int    当前段位需求威望
        --CombatBUFFID: list_int    战魂BUFF等级
        --KillPrestige: int    被击杀基本威望
        --PrestigeDecrease: int    每天威望开始衰减值
        --PrestigeAddition: int    获得威望加成
        --Salary: int    战阶俸禄
        --Reward1: list_int    战阶奖励1
        --Reward2: list_int    战阶奖励2
        --Reward3: list_int    战阶奖励3
        --Reward4: list_int    战阶奖励4
        [1] = { 
            ID = 1,
            Lv = 0,
            Name = 0,
            Name1 = "兵勇1",
            RequirePrestige = 0,
            CombatBUFFID = {513, 1, },
            KillPrestige = 70,
            PrestigeDecrease = 2400,
            PrestigeAddition = 0,
            Salary = 0,
            Reward1 = {1013, 10, },
            Reward2 = {4026, 1, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [2] = { 
            ID = 2,
            Lv = 10,
            Name = 0,
            Name1 = "兵勇2",
            RequirePrestige = 1000,
            CombatBUFFID = {513, 2, },
            KillPrestige = 100,
            PrestigeDecrease = 2400,
            PrestigeAddition = 5,
            Salary = 100,
            Reward1 = {1013, 15, },
            Reward2 = {4026, 1, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [3] = { 
            ID = 3,
            Lv = 25,
            Name = 0,
            Name1 = "兵勇3",
            RequirePrestige = 3000,
            CombatBUFFID = {513, 3, },
            KillPrestige = 130,
            PrestigeDecrease = 2400,
            PrestigeAddition = 10,
            Salary = 120,
            Reward1 = {1013, 20, },
            Reward2 = {4026, 1, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [4] = { 
            ID = 4,
            Lv = 30,
            Name = 0,
            Name1 = "力士1",
            RequirePrestige = 3500,
            CombatBUFFID = {513, 4, },
            KillPrestige = 160,
            PrestigeDecrease = 2400,
            PrestigeAddition = 15,
            Salary = 140,
            Reward1 = {1013, 25, },
            Reward2 = {4026, 1, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [5] = { 
            ID = 5,
            Lv = 35,
            Name = 0,
            Name1 = "力士2",
            RequirePrestige = 3500,
            CombatBUFFID = {513, 5, },
            KillPrestige = 190,
            PrestigeDecrease = 2400,
            PrestigeAddition = 20,
            Salary = 160,
            Reward1 = {1013, 30, },
            Reward2 = {4026, 1, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [6] = { 
            ID = 6,
            Lv = 40,
            Name = 0,
            Name1 = "力士3",
            RequirePrestige = 4000,
            CombatBUFFID = {513, 6, },
            KillPrestige = 220,
            PrestigeDecrease = 2400,
            PrestigeAddition = 25,
            Salary = 180,
            Reward1 = {1013, 35, },
            Reward2 = {4026, 2, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [7] = { 
            ID = 7,
            Lv = 45,
            Name = 0,
            Name1 = "护军参领1",
            RequirePrestige = 4000,
            CombatBUFFID = {513, 7, },
            KillPrestige = 250,
            PrestigeDecrease = 2400,
            PrestigeAddition = 30,
            Salary = 200,
            Reward1 = {1013, 40, },
            Reward2 = {4026, 2, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [8] = { 
            ID = 8,
            Lv = 50,
            Name = 0,
            Name1 = "护军参领2",
            RequirePrestige = 4500,
            CombatBUFFID = {513, 8, },
            KillPrestige = 280,
            PrestigeDecrease = 2400,
            PrestigeAddition = 35,
            Salary = 220,
            Reward1 = {1013, 45, },
            Reward2 = {4026, 2, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [9] = { 
            ID = 9,
            Lv = 50,
            Name = 0,
            Name1 = "护军参领3",
            RequirePrestige = 5000,
            CombatBUFFID = {513, 9, },
            KillPrestige = 310,
            PrestigeDecrease = 2400,
            PrestigeAddition = 40,
            Salary = 240,
            Reward1 = {1013, 50, },
            Reward2 = {4026, 2, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [10] = { 
            ID = 10,
            Lv = 55,
            Name = 0,
            Name1 = "前锋参领1",
            RequirePrestige = 5500,
            CombatBUFFID = {513, 10, },
            KillPrestige = 340,
            PrestigeDecrease = 2400,
            PrestigeAddition = 45,
            Salary = 260,
            Reward1 = {1013, 55, },
            Reward2 = {4026, 2, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [11] = { 
            ID = 11,
            Lv = 60,
            Name = 0,
            Name1 = "前锋参领2",
            RequirePrestige = 5500,
            CombatBUFFID = {513, 11, },
            KillPrestige = 345,
            PrestigeDecrease = 2500,
            PrestigeAddition = 50,
            Salary = 280,
            Reward1 = {1013, 60, },
            Reward2 = {4026, 2, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [12] = { 
            ID = 12,
            Lv = 65,
            Name = 0,
            Name1 = "前锋参领3",
            RequirePrestige = 6000,
            CombatBUFFID = {513, 12, },
            KillPrestige = 350,
            PrestigeDecrease = 2500,
            PrestigeAddition = 55,
            Salary = 300,
            Reward1 = {1013, 65, },
            Reward2 = {4026, 2, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [13] = { 
            ID = 13,
            Lv = 70,
            Name = 0,
            Name1 = "仁勇校尉1",
            RequirePrestige = 6500,
            CombatBUFFID = {513, 13, },
            KillPrestige = 355,
            PrestigeDecrease = 2600,
            PrestigeAddition = 60,
            Salary = 320,
            Reward1 = {1013, 70, },
            Reward2 = {4026, 2, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [14] = { 
            ID = 14,
            Lv = 70,
            Name = 0,
            Name1 = "仁勇校尉2",
            RequirePrestige = 7000,
            CombatBUFFID = {513, 14, },
            KillPrestige = 360,
            PrestigeDecrease = 2700,
            PrestigeAddition = 65,
            Salary = 340,
            Reward1 = {1013, 75, },
            Reward2 = {4026, 2, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [15] = { 
            ID = 15,
            Lv = 75,
            Name = 0,
            Name1 = "仁勇校尉3",
            RequirePrestige = 7500,
            CombatBUFFID = {513, 15, },
            KillPrestige = 365,
            PrestigeDecrease = 2800,
            PrestigeAddition = 70,
            Salary = 360,
            Reward1 = {1013, 80, },
            Reward2 = {4026, 2, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [16] = { 
            ID = 16,
            Lv = 80,
            Name = 0,
            Name1 = "宣节校尉1",
            RequirePrestige = 8000,
            CombatBUFFID = {513, 16, },
            KillPrestige = 370,
            PrestigeDecrease = 2800,
            PrestigeAddition = 75,
            Salary = 380,
            Reward1 = {1013, 85, },
            Reward2 = {4026, 3, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [17] = { 
            ID = 17,
            Lv = 85,
            Name = 0,
            Name1 = "宣节校尉2",
            RequirePrestige = 7500,
            CombatBUFFID = {513, 17, },
            KillPrestige = 375,
            PrestigeDecrease = 2900,
            PrestigeAddition = 80,
            Salary = 400,
            Reward1 = {1013, 90, },
            Reward2 = {4026, 3, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [18] = { 
            ID = 18,
            Lv = 85,
            Name = 0,
            Name1 = "宣节校尉3",
            RequirePrestige = 11000,
            CombatBUFFID = {513, 18, },
            KillPrestige = 380,
            PrestigeDecrease = 3000,
            PrestigeAddition = 85,
            Salary = 420,
            Reward1 = {1013, 95, },
            Reward2 = {4026, 3, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [19] = { 
            ID = 19,
            Lv = 90,
            Name = 0,
            Name1 = "振威校尉1",
            RequirePrestige = 11500,
            CombatBUFFID = {513, 19, },
            KillPrestige = 385,
            PrestigeDecrease = 3100,
            PrestigeAddition = 90,
            Salary = 440,
            Reward1 = {1013, 100, },
            Reward2 = {4026, 3, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [20] = { 
            ID = 20,
            Lv = 90,
            Name = 0,
            Name1 = "振威校尉2",
            RequirePrestige = 12000,
            CombatBUFFID = {513, 20, },
            KillPrestige = 390,
            PrestigeDecrease = 3200,
            PrestigeAddition = 95,
            Salary = 460,
            Reward1 = {1013, 105, },
            Reward2 = {4026, 3, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [21] = { 
            ID = 21,
            Lv = 95,
            Name = 0,
            Name1 = "振威校尉3",
            RequirePrestige = 14500,
            CombatBUFFID = {513, 21, },
            KillPrestige = 395,
            PrestigeDecrease = 3200,
            PrestigeAddition = 100,
            Salary = 480,
            Reward1 = {1013, 110, },
            Reward2 = {4026, 3, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [22] = { 
            ID = 22,
            Lv = 95,
            Name = 0,
            Name1 = "昭武校尉1",
            RequirePrestige = 15000,
            CombatBUFFID = {513, 22, },
            KillPrestige = 400,
            PrestigeDecrease = 3300,
            PrestigeAddition = 105,
            Salary = 500,
            Reward1 = {1013, 115, },
            Reward2 = {4026, 3, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [23] = { 
            ID = 23,
            Lv = 100,
            Name = 0,
            Name1 = "昭武校尉2",
            RequirePrestige = 15500,
            CombatBUFFID = {513, 23, },
            KillPrestige = 405,
            PrestigeDecrease = 3400,
            PrestigeAddition = 110,
            Salary = 520,
            Reward1 = {1013, 120, },
            Reward2 = {4026, 3, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [24] = { 
            ID = 24,
            Lv = 100,
            Name = 0,
            Name1 = "昭武校尉3",
            RequirePrestige = 16000,
            CombatBUFFID = {513, 24, },
            KillPrestige = 410,
            PrestigeDecrease = 3500,
            PrestigeAddition = 115,
            Salary = 540,
            Reward1 = {1013, 125, },
            Reward2 = {4026, 3, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [25] = { 
            ID = 25,
            Lv = 100,
            Name = 0,
            Name1 = "宣威中郎将1",
            RequirePrestige = 16500,
            CombatBUFFID = {513, 25, },
            KillPrestige = 415,
            PrestigeDecrease = 3600,
            PrestigeAddition = 120,
            Salary = 560,
            Reward1 = {1013, 130, },
            Reward2 = {4026, 3, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [26] = { 
            ID = 26,
            Lv = 105,
            Name = 0,
            Name1 = "宣威中郎将2",
            RequirePrestige = 22000,
            CombatBUFFID = {513, 26, },
            KillPrestige = 420,
            PrestigeDecrease = 3700,
            PrestigeAddition = 125,
            Salary = 580,
            Reward1 = {1013, 135, },
            Reward2 = {4026, 4, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [27] = { 
            ID = 27,
            Lv = 105,
            Name = 0,
            Name1 = "宣威中郎将3",
            RequirePrestige = 23000,
            CombatBUFFID = {513, 27, },
            KillPrestige = 425,
            PrestigeDecrease = 3800,
            PrestigeAddition = 130,
            Salary = 600,
            Reward1 = {1013, 140, },
            Reward2 = {4026, 4, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [28] = { 
            ID = 28,
            Lv = 110,
            Name = 0,
            Name1 = "归德中朗将1",
            RequirePrestige = 23500,
            CombatBUFFID = {513, 28, },
            KillPrestige = 430,
            PrestigeDecrease = 3900,
            PrestigeAddition = 135,
            Salary = 620,
            Reward1 = {1013, 145, },
            Reward2 = {4026, 4, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [29] = { 
            ID = 29,
            Lv = 110,
            Name = 0,
            Name1 = "归德中朗将2",
            RequirePrestige = 24000,
            CombatBUFFID = {513, 29, },
            KillPrestige = 435,
            PrestigeDecrease = 4000,
            PrestigeAddition = 140,
            Salary = 640,
            Reward1 = {1013, 150, },
            Reward2 = {4026, 4, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [30] = { 
            ID = 30,
            Lv = 110,
            Name = 0,
            Name1 = "归德中朗将3",
            RequirePrestige = 25000,
            CombatBUFFID = {513, 30, },
            KillPrestige = 440,
            PrestigeDecrease = 4000,
            PrestigeAddition = 145,
            Salary = 660,
            Reward1 = {1013, 155, },
            Reward2 = {4026, 4, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [31] = { 
            ID = 31,
            Lv = 115,
            Name = 0,
            Name1 = "怀化中朗将1",
            RequirePrestige = 37500,
            CombatBUFFID = {513, 31, },
            KillPrestige = 445,
            PrestigeDecrease = 4100,
            PrestigeAddition = 150,
            Salary = 680,
            Reward1 = {1013, 160, },
            Reward2 = {4026, 4, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [32] = { 
            ID = 32,
            Lv = 115,
            Name = 0,
            Name1 = "怀化中朗将2",
            RequirePrestige = 38500,
            CombatBUFFID = {513, 32, },
            KillPrestige = 450,
            PrestigeDecrease = 4200,
            PrestigeAddition = 155,
            Salary = 700,
            Reward1 = {1013, 165, },
            Reward2 = {4026, 4, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [33] = { 
            ID = 33,
            Lv = 120,
            Name = 0,
            Name1 = "怀化中朗将3",
            RequirePrestige = 39500,
            CombatBUFFID = {513, 33, },
            KillPrestige = 455,
            PrestigeDecrease = 4300,
            PrestigeAddition = 160,
            Salary = 720,
            Reward1 = {1013, 170, },
            Reward2 = {4026, 4, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [34] = { 
            ID = 34,
            Lv = 120,
            Name = 0,
            Name1 = "忠武将军1",
            RequirePrestige = 40500,
            CombatBUFFID = {513, 34, },
            KillPrestige = 460,
            PrestigeDecrease = 4400,
            PrestigeAddition = 165,
            Salary = 740,
            Reward1 = {1013, 175, },
            Reward2 = {4026, 4, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [35] = { 
            ID = 35,
            Lv = 120,
            Name = 0,
            Name1 = "忠武将军2",
            RequirePrestige = 41500,
            CombatBUFFID = {513, 35, },
            KillPrestige = 465,
            PrestigeDecrease = 4500,
            PrestigeAddition = 170,
            Salary = 760,
            Reward1 = {1013, 180, },
            Reward2 = {4026, 4, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [36] = { 
            ID = 36,
            Lv = 125,
            Name = 0,
            Name1 = "忠武将军3",
            RequirePrestige = 49000,
            CombatBUFFID = {513, 36, },
            KillPrestige = 470,
            PrestigeDecrease = 4600,
            PrestigeAddition = 175,
            Salary = 780,
            Reward1 = {1013, 185, },
            Reward2 = {4026, 5, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [37] = { 
            ID = 37,
            Lv = 125,
            Name = 0,
            Name1 = "归德将军1",
            RequirePrestige = 50500,
            CombatBUFFID = {513, 37, },
            KillPrestige = 475,
            PrestigeDecrease = 4800,
            PrestigeAddition = 180,
            Salary = 800,
            Reward1 = {1013, 190, },
            Reward2 = {4026, 5, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [38] = { 
            ID = 38,
            Lv = 130,
            Name = 0,
            Name1 = "归德将军2",
            RequirePrestige = 51500,
            CombatBUFFID = {513, 38, },
            KillPrestige = 480,
            PrestigeDecrease = 4900,
            PrestigeAddition = 185,
            Salary = 820,
            Reward1 = {1013, 195, },
            Reward2 = {4026, 5, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [39] = { 
            ID = 39,
            Lv = 130,
            Name = 0,
            Name1 = "归德将军3",
            RequirePrestige = 53000,
            CombatBUFFID = {513, 39, },
            KillPrestige = 485,
            PrestigeDecrease = 5000,
            PrestigeAddition = 190,
            Salary = 840,
            Reward1 = {1013, 200, },
            Reward2 = {4026, 5, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [40] = { 
            ID = 40,
            Lv = 130,
            Name = 0,
            Name1 = "云麾将军1",
            RequirePrestige = 54000,
            CombatBUFFID = {513, 40, },
            KillPrestige = 490,
            PrestigeDecrease = 5100,
            PrestigeAddition = 195,
            Salary = 860,
            Reward1 = {1013, 205, },
            Reward2 = {4026, 5, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [41] = { 
            ID = 41,
            Lv = 135,
            Name = 0,
            Name1 = "云麾将军2",
            RequirePrestige = 62500,
            CombatBUFFID = {513, 41, },
            KillPrestige = 495,
            PrestigeDecrease = 5200,
            PrestigeAddition = 200,
            Salary = 880,
            Reward1 = {1013, 210, },
            Reward2 = {4026, 5, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [42] = { 
            ID = 42,
            Lv = 135,
            Name = 0,
            Name1 = "怀化将军1",
            RequirePrestige = 64000,
            CombatBUFFID = {513, 42, },
            KillPrestige = 500,
            PrestigeDecrease = 5300,
            PrestigeAddition = 205,
            Salary = 900,
            Reward1 = {1013, 215, },
            Reward2 = {4026, 5, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [43] = { 
            ID = 43,
            Lv = 140,
            Name = 0,
            Name1 = "怀化将军2",
            RequirePrestige = 65500,
            CombatBUFFID = {513, 43, },
            KillPrestige = 505,
            PrestigeDecrease = 5400,
            PrestigeAddition = 210,
            Salary = 920,
            Reward1 = {1013, 220, },
            Reward2 = {4026, 5, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [44] = { 
            ID = 44,
            Lv = 140,
            Name = 0,
            Name1 = "冠军大将军1",
            RequirePrestige = 67000,
            CombatBUFFID = {513, 44, },
            KillPrestige = 510,
            PrestigeDecrease = 5500,
            PrestigeAddition = 215,
            Salary = 940,
            Reward1 = {1013, 225, },
            Reward2 = {4026, 5, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [45] = { 
            ID = 45,
            Lv = 140,
            Name = 0,
            Name1 = "冠军大将军2",
            RequirePrestige = 69000,
            CombatBUFFID = {513, 45, },
            KillPrestige = 515,
            PrestigeDecrease = 5600,
            PrestigeAddition = 220,
            Salary = 960,
            Reward1 = {1013, 230, },
            Reward2 = {4026, 5, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [46] = { 
            ID = 46,
            Lv = 145,
            Name = 0,
            Name1 = "镇军大将军1",
            RequirePrestige = 70500,
            CombatBUFFID = {513, 46, },
            KillPrestige = 520,
            PrestigeDecrease = 5800,
            PrestigeAddition = 225,
            Salary = 980,
            Reward1 = {1013, 235, },
            Reward2 = {4026, 6, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [47] = { 
            ID = 47,
            Lv = 145,
            Name = 0,
            Name1 = "镇军大将军2",
            RequirePrestige = 72000,
            CombatBUFFID = {513, 47, },
            KillPrestige = 525,
            PrestigeDecrease = 5900,
            PrestigeAddition = 230,
            Salary = 1000,
            Reward1 = {1013, 240, },
            Reward2 = {4026, 6, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [48] = { 
            ID = 48,
            Lv = 150,
            Name = 0,
            Name1 = "辅国大将军1",
            RequirePrestige = 73500,
            CombatBUFFID = {513, 48, },
            KillPrestige = 530,
            PrestigeDecrease = 6000,
            PrestigeAddition = 235,
            Salary = 1020,
            Reward1 = {1013, 245, },
            Reward2 = {4026, 6, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [49] = { 
            ID = 49,
            Lv = 150,
            Name = 0,
            Name1 = "辅国大将军2",
            RequirePrestige = 75500,
            CombatBUFFID = {513, 49, },
            KillPrestige = 535,
            PrestigeDecrease = 6100,
            PrestigeAddition = 240,
            Salary = 1040,
            Reward1 = {1013, 250, },
            Reward2 = {4026, 6, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
        [50] = { 
            ID = 50,
            Lv = 150,
            Name = 0,
            Name1 = "骠骑大将军",
            RequirePrestige = 77000,
            CombatBUFFID = {513, 50, },
            KillPrestige = 540,
            PrestigeDecrease = 6200,
            PrestigeAddition = 245,
            Salary = 1060,
            Reward1 = {1013, 255, },
            Reward2 = {4026, 6, },
            Reward3 = {4108, 1, },
            Reward4 = {},
        },
    },

    ["ElectionQualification"] = {
        --office: string    官职
        --officeID: int    官职ID
        --liveness: int    本周活跃度排名
        --fight: int    战力条件排名
        --kindness: int    善恶值条件排名
        --exploit: int    上次大攻防功勋排名
        [1] = { 
            office = "皇帝",
            officeID = 1,
            liveness = -1,
            fight = 1000,
            kindness = -1,
            exploit = -1,
        },
        [2] = { 
            office = "丞相",
            officeID = 2,
            liveness = -1,
            fight = 1000,
            kindness = -1,
            exploit = -1,
        },
        [3] = { 
            office = "大将军",
            officeID = 3,
            liveness = -1,
            fight = 1000,
            kindness = -1,
            exploit = -1,
        },
        [4] = { 
            office = "中书令",
            officeID = 4,
            liveness = -1,
            fight = 1000,
            kindness = -1,
            exploit = -1,
        },
        [5] = { 
            office = "门下侍中",
            officeID = 5,
            liveness = -1,
            fight = 1000,
            kindness = -1,
            exploit = -1,
        },
        [6] = { 
            office = "尚书令",
            officeID = 6,
            liveness = -1,
            fight = 1000,
            kindness = -1,
            exploit = -1,
        },
        [7] = { 
            office = "偏将",
            officeID = 7,
            liveness = -1,
            fight = 1000,
            kindness = -1,
            exploit = -1,
        },
        [8] = { 
            office = "都统",
            officeID = 8,
            liveness = -1,
            fight = 1000,
            kindness = -1,
            exploit = -1,
        },
        [9] = { 
            office = "提督",
            officeID = 9,
            liveness = -1,
            fight = 1000,
            kindness = -1,
            exploit = -1,
        },
    },

    ["DiscountFunction"] = {
        --ID: int    官职ID
        --office: string    对应官职
        --discount: int    折扣力度
        --lasttime: int    持续时间
        --int: int    次数
        [1] = { 
            ID = 1,
            office = "皇帝",
            discount = 70,
            lasttime = 120,
            int = 5,
        },
        [2] = { 
            ID = 2,
            office = "丞相",
            discount = 90,
            lasttime = 60,
            int = 3,
        },
        [3] = { 
            ID = 3,
            office = "大将军",
            discount = 90,
            lasttime = 60,
            int = 3,
        },
        [4] = { 
            ID = 4,
            office = "中书令",
            discount = 90,
            lasttime = 60,
            int = 3,
        },
        [5] = { 
            ID = 5,
            office = "门下侍中",
            discount = 90,
            lasttime = 60,
            int = 3,
        },
        [6] = { 
            ID = 6,
            office = "尚书令",
            discount = 90,
            lasttime = 60,
            int = 3,
        },
        [7] = { 
            ID = 7,
            office = "偏将",
            discount = 90,
            lasttime = 60,
            int = 3,
        },
        [8] = { 
            ID = 8,
            office = "都统",
            discount = 90,
            lasttime = 60,
            int = 3,
        },
        [9] = { 
            ID = 9,
            office = "提督",
            discount = 90,
            lasttime = 60,
            int = 3,
        },
    },

    ["NobleRank2"] = {
        --ID: int    ID
        --Ranking: int    所需排名下限
        --Gain: int    灵力值增益
        [1] = { 
            ID = 1,
            Ranking = 1,
            Gain = 12,
        },
        [2] = { 
            ID = 2,
            Ranking = 2,
            Gain = 11,
        },
        [3] = { 
            ID = 3,
            Ranking = 3,
            Gain = 10,
        },
        [4] = { 
            ID = 4,
            Ranking = 10,
            Gain = 9,
        },
        [5] = { 
            ID = 5,
            Ranking = 20,
            Gain = 8,
        },
        [6] = { 
            ID = 6,
            Ranking = 30,
            Gain = 7,
        },
        [7] = { 
            ID = 7,
            Ranking = 40,
            Gain = 6,
        },
        [8] = { 
            ID = 8,
            Ranking = 50,
            Gain = 5,
        },
        [9] = { 
            ID = 9,
            Ranking = 100,
            Gain = 4,
        },
        [10] = { 
            ID = 10,
            Ranking = 150,
            Gain = 3,
        },
        [11] = { 
            ID = 11,
            Ranking = 200,
            Gain = 2,
        },
        [12] = { 
            ID = 12,
            Ranking = 300,
            Gain = 1,
        },
        [13] = { 
            ID = 13,
            Ranking = -1,
            Gain = 0,
        },
    },

    ["Parameter"] = {
        --ID: int    参数ID
        --Value: string    值
        --Describe: string    说明
        [1] = { 
            ID = 1,
            Value = "5|0",
            Describe = "升级战阶时间，和刷新战阶奖励时间（先升战阶，再刷新奖励。",
        },
        [2] = { 
            ID = 2,
            Value = "300000.0",
            Describe = "击杀同一玩家不获得威望的时间，单位（毫秒）",
        },
        [3] = { 
            ID = 3,
            Value = "",
            Describe = "弃用",
        },
        [4] = { 
            ID = 4,
            Value = "5.0",
            Describe = "战魂BUFF消耗的威望值，百分制。",
        },
        [5] = { 
            ID = 5,
            Value = "",
            Describe = "弃用，走战魂BUFF逻辑",
        },
        [6] = { 
            ID = 6,
            Value = "10.0",
            Describe = "威望衰减参数，百分制。",
        },
        [7] = { 
            ID = 7,
            Value = "1000.0",
            Describe = "捐献最小基础值，也是默认值，单位（铜钱）",
        },
        [8] = { 
            ID = 8,
            Value = "20.0",
            Describe = "当前战阶开放阶段，单位（阶）",
        },
        [9] = { 
            ID = 9,
            Value = "2.0",
            Describe = "捐献周榜重置的日期，2表示星期一（从星期日开始算）",
        },
        [10] = { 
            ID = 10,
            Value = "0|1",
            Describe = "周榜重置的时间。0|0是时间表达格式，|前面是小时，|后边是分。",
        },
        [11] = { 
            ID = 11,
            Value = "4.0",
            Describe = "弃用，走选举结算时间",
        },
        [12] = { 
            ID = 12,
            Value = "12|00",
            Describe = "弃用，走选举结算时间",
        },
        [13] = { 
            ID = 13,
            Value = "5.0",
            Describe = "弃用，统一填到选举时间一栏",
        },
        [14] = { 
            ID = 14,
            Value = "00|00",
            Describe = "弃用，统一填到选举时间一栏",
        },
        [15] = { 
            ID = 15,
            Value = "1000.0",
            Describe = "选举编号开始值",
        },
        [16] = { 
            ID = 16,
            Value = "120.0",
            Describe = "弃用，统一填到官职技能参数一栏",
        },
        [17] = { 
            ID = 17,
            Value = "10.0",
            Describe = "弃用，统一填到官职技能参数一栏",
        },
    },

    ["GovernmentPost"] = {
        --ID: int    ID
        --name: string    官职
        --grade: int    官职等级
        --describe: string    官职说明
        --salary: int    每日俸禄
        --convene: int    阵营召集
        --opentask: int    开启阵营任务
        --openfacility: int    开启阵营设施状态
        --openBOSS: int    开启BOSS状态
        --officerskill1CD: int    全体技能冷却时间
        --officerskill1BUFF: int    阵营全体BUFF
        --officerskill2: int    光环技能
        --adjustablesoldiers: int    阵营调兵
        --discount: int    打折功能
        --openportal: int    开关传送阵
        --paysalary : int    发放俸禄
        [1] = { 
            ID = 1,
            name = "皇帝",
            grade = 1,
            describe = "",
            salary = 250000,
            convene = 1,
            opentask = 0,
            openfacility = 0,
            openBOSS = 0,
            officerskill1CD = 24,
            officerskill1BUFF = 1009,
            officerskill2 = 26,
            adjustablesoldiers = 0,
            discount = 1,
            openportal = 0,
            paysalary  = 1,
        },
        [2] = { 
            ID = 2,
            name = "丞相",
            grade = 2,
            describe = "",
            salary = 210000,
            convene = 0,
            opentask = 0,
            openfacility = 0,
            openBOSS = 0,
            officerskill1CD = 24,
            officerskill1BUFF = 1010,
            officerskill2 = 27,
            adjustablesoldiers = 0,
            discount = 1,
            openportal = 0,
            paysalary  = 1,
        },
        [3] = { 
            ID = 3,
            name = "大将军",
            grade = 3,
            describe = "",
            salary = 210000,
            convene = 1,
            opentask = 0,
            openfacility = 0,
            openBOSS = 0,
            officerskill1CD = 24,
            officerskill1BUFF = 1011,
            officerskill2 = 28,
            adjustablesoldiers = 0,
            discount = 0,
            openportal = 0,
            paysalary  = 0,
        },
        [4] = { 
            ID = 4,
            name = "中书令",
            grade = 4,
            describe = "",
            salary = 100000,
            convene = 0,
            opentask = 0,
            openfacility = 0,
            openBOSS = 0,
            officerskill1CD = 0,
            officerskill1BUFF = 0,
            officerskill2 = 29,
            adjustablesoldiers = 0,
            discount = 1,
            openportal = 0,
            paysalary  = 1,
        },
        [5] = { 
            ID = 5,
            name = "门下侍中",
            grade = 6,
            describe = "",
            salary = 80000,
            convene = 0,
            opentask = 0,
            openfacility = 0,
            openBOSS = 0,
            officerskill1CD = 0,
            officerskill1BUFF = 0,
            officerskill2 = 30,
            adjustablesoldiers = 0,
            discount = 1,
            openportal = 0,
            paysalary  = 1,
        },
        [6] = { 
            ID = 6,
            name = "尚书令",
            grade = 8,
            describe = "",
            salary = 50000,
            convene = 0,
            opentask = 0,
            openfacility = 0,
            openBOSS = 0,
            officerskill1CD = 0,
            officerskill1BUFF = 0,
            officerskill2 = 31,
            adjustablesoldiers = 0,
            discount = 1,
            openportal = 0,
            paysalary  = 1,
        },
        [7] = { 
            ID = 7,
            name = "偏将",
            grade = 5,
            describe = "",
            salary = 100000,
            convene = 0,
            opentask = 0,
            openfacility = 0,
            openBOSS = 0,
            officerskill1CD = 0,
            officerskill1BUFF = 0,
            officerskill2 = 32,
            adjustablesoldiers = 0,
            discount = 0,
            openportal = 0,
            paysalary  = 0,
        },
        [8] = { 
            ID = 8,
            name = "都统",
            grade = 7,
            describe = "",
            salary = 80000,
            convene = 0,
            opentask = 0,
            openfacility = 0,
            openBOSS = 0,
            officerskill1CD = 0,
            officerskill1BUFF = 0,
            officerskill2 = 33,
            adjustablesoldiers = 0,
            discount = 0,
            openportal = 0,
            paysalary  = 0,
        },
        [9] = { 
            ID = 9,
            name = "提督",
            grade = 9,
            describe = "",
            salary = 50000,
            convene = 0,
            opentask = 0,
            openfacility = 0,
            openBOSS = 0,
            officerskill1CD = 0,
            officerskill1BUFF = 0,
            officerskill2 = 34,
            adjustablesoldiers = 0,
            discount = 0,
            openportal = 0,
            paysalary  = 0,
        },
    },

    ["NobleRank"] = {
        --ID: int    ID
        --Name: int    爵位名称
        --Name1: string    爵位名称-策划用
        --Donate: int    所需捐献值
        --Ranking: int    所需排名下限
        --Gain: int    灵力值增益
        --Describe: string    爵位说明
        [1] = { 
            ID = 1,
            Name = 0,
            Name1 = "亲王",
            Donate = -1,
            Ranking = 1,
            Gain = 30,
            Describe = "捐献排位第1名",
        },
        [2] = { 
            ID = 2,
            Name = 0,
            Name1 = "郡王",
            Donate = -1,
            Ranking = 3,
            Gain = 25,
            Describe = "捐献排位前3名",
        },
        [3] = { 
            ID = 3,
            Name = 0,
            Name1 = "镇国公",
            Donate = -1,
            Ranking = 30,
            Gain = 20,
            Describe = "捐献排位前30名",
        },
        [4] = { 
            ID = 4,
            Name = 0,
            Name1 = "辅国公",
            Donate = -1,
            Ranking = 100,
            Gain = 16,
            Describe = "捐献排位前100名",
        },
        [5] = { 
            ID = 5,
            Name = 0,
            Name1 = "乡侯",
            Donate = 60000000,
            Ranking = 200,
            Gain = 13,
            Describe = "捐献排位前200名或者捐献铜钱到达6千万。",
        },
        [6] = { 
            ID = 6,
            Name = 0,
            Name1 = "亭侯",
            Donate = 30000000,
            Ranking = 300,
            Gain = 11,
            Describe = "捐献排位前300名或者捐献铜钱到达3千万。",
        },
        [7] = { 
            ID = 7,
            Name = 0,
            Name1 = "一等伯爵",
            Donate = 10000000,
            Ranking = 500,
            Gain = 9,
            Describe = "捐献排位前500名或者捐献铜钱到达1千万。",
        },
        [8] = { 
            ID = 8,
            Name = 0,
            Name1 = "二等伯爵",
            Donate = 2000000,
            Ranking = -1,
            Gain = 7,
            Describe = "捐献铜钱到达200万。",
        },
        [9] = { 
            ID = 9,
            Name = 0,
            Name1 = "一等子爵",
            Donate = 500000,
            Ranking = -1,
            Gain = 5,
            Describe = "捐献铜钱到达50万。",
        },
        [10] = { 
            ID = 10,
            Name = 0,
            Name1 = "二等子爵",
            Donate = 100000,
            Ranking = -1,
            Gain = 3,
            Describe = "捐献铜钱到达10万。",
        },
        [11] = { 
            ID = 11,
            Name = 0,
            Name1 = "男爵",
            Donate = 10000,
            Ranking = -1,
            Gain = 1,
            Describe = "捐献铜钱到达1万。",
        },
        [12] = { 
            ID = 12,
            Name = 0,
            Name1 = "平民",
            Donate = 0,
            Ranking = -1,
            Gain = 0,
            Describe = "普通民众。",
        },
    },

}
