-- This is generate by program !!!
-- Don't change it manaully. 
-- GenerateTime: '2017-06-26 14:29:06'

return { 
    ["ChannelContent"] = {
        --ID: int    ID
        --ChannelName: int    名称
        --ChannelName1: string    名称
        --OpenLevel: int    开放等级
        --Condition: string    条件限制
        --VoiceChat: int    支持语音聊天
        --TextChat: int    支持文字聊天
        --Consumption: list_int    消耗物品
        --ChatInterval: int    发话间隔
        [1] = { 
            ID = 1,
            ChannelName = 0,
            ChannelName1 = "公会频道",
            OpenLevel = 1,
            Condition = "加入公会",
            VoiceChat = 1,
            TextChat = 1,
            Consumption = {0, },
            ChatInterval = 2,
        },
        [2] = { 
            ID = 2,
            ChannelName = 0,
            ChannelName1 = "喇叭频道",
            OpenLevel = 1,
            Condition = "0.0",
            VoiceChat = 0,
            TextChat = 1,
            Consumption = {4034, 1, },
            ChatInterval = 1,
        },
        [3] = { 
            ID = 3,
            ChannelName = 0,
            ChannelName1 = "队伍频道",
            OpenLevel = 1,
            Condition = "加入队伍",
            VoiceChat = 1,
            TextChat = 1,
            Consumption = {0, },
            ChatInterval = 2,
        },
        [4] = { 
            ID = 4,
            ChannelName = 0,
            ChannelName1 = "附近频道",
            OpenLevel = 1,
            Condition = "在玩家一定范围内",
            VoiceChat = 1,
            TextChat = 1,
            Consumption = {0, },
            ChatInterval = 2,
        },
        [5] = { 
            ID = 5,
            ChannelName = 0,
            ChannelName1 = "系统频道",
            OpenLevel = 1,
            Condition = "0.0",
            VoiceChat = 0,
            TextChat = 0,
            Consumption = {0},
            ChatInterval = 0,
        },
        [6] = { 
            ID = 6,
            ChannelName = 0,
            ChannelName1 = "阵营频道",
            OpenLevel = 1,
            Condition = "0.0",
            VoiceChat = 0,
            TextChat = 0,
            Consumption = {0, },
            ChatInterval = 5,
        },
    },

    ["SystemMessage"] = {
        --ID: int    ID
        --MessageType: int    消息类型
        --Name: int    名称
        --Name1: string    名称
        --TextContent: int    文本内容
        --TextContent1: string    文本内容
        --Notice: int    是否公告
        --FriendChatDisplay: int    是否在好友聊天显示
        --Repeat: list_int    重复次数
        [1001] = { 
            ID = 1001,
            MessageType = 3,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "%s真厉害运气太好了！在%s中获得了props，实在令人羡慕！",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [1002] = { 
            ID = 1002,
            MessageType = 3,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "恭喜你升到%d级",
            Notice = 0,
            FriendChatDisplay = 1,
            Repeat = {},
        },
        [1003] = { 
            ID = 1003,
            MessageType = 2,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "<color=#FFFFFF>国庆活动已经开启，玩家可以至远古战场找蚩尤报名国庆活动。</color>",
            Notice = 1,
            FriendChatDisplay = 1,
            Repeat = {},
        },
        [1004] = { 
            ID = 1004,
            MessageType = 1,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "<color=#FFFFFF>为了给玩家创造更加安全稳定的游戏环境，服务器将在%d月%d日%d时开启新版本更新维护，预计停机%d小时。详细维护内容详见通灵宝印官网。</color>",
            Notice = 1,
            FriendChatDisplay = 1,
            Repeat = {5, 10, },
        },
        [1005] = { 
            ID = 1005,
            MessageType = 3,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "<color=#FFFFFF>大侠你回来啦</color>距离上次离线累计时间为%d分钟，获得离线经验：%d",
            Notice = 0,
            FriendChatDisplay = 1,
            Repeat = {},
        },
        [1006] = { 
            ID = 1006,
            MessageType = 4,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "<color=#FFFFFF>阵营大战已经开启，玩家可以通过地图传送至远古战场进行战斗啦！</color>",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [1007] = { 
            ID = 1007,
            MessageType = 1,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，通灵宝印游戏将在%d分钟后进行临时维护更新，服务器将会重启。为了保证玩家帐号信息稳定，请大家即时下线以免发生帐号数据问题，感谢大家的配合！",
            Notice = 1,
            FriendChatDisplay = 1,
            Repeat = {5, 10, },
        },
        [1008] = { 
            ID = 1008,
            MessageType = 1,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "通灵小管家提示：抵制不良游戏,拒绝盗版游戏。注意自我保护,谨防上当受骗。适度游戏益脑,沉迷游戏伤身。合理安排时间,享受健康生活。",
            Notice = 1,
            FriendChatDisplay = 1,
            Repeat = {},
        },
        [1009] = { 
            ID = 1009,
            MessageType = 1,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，通灵宝印游戏封测将于%d月%d日%d时结束。感谢各位玩家的帮助与反馈，在这段时间，我们一起享受着游戏的快乐，一起在这里燃烧激情，共同讨论着通灵宝印带给我们的各种惊喜与难忘。我们将根据本次测试的情况，对今后游戏的各个方面进行完善。期待下次与您相见，更多封测活动奖励请关注官网信息。",
            Notice = 1,
            FriendChatDisplay = 1,
            Repeat = {5, 10, },
        },
        [1010] = { 
            ID = 1010,
            MessageType = 1,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，通灵宝印游戏将在%d月%d日%d时%d分钟后进行服务器版本更新，服务器将会关闭。为了保证玩家帐号信息稳定，请大家即时下线以免发生帐号数据问题，感谢大家的配合！",
            Notice = 1,
            FriendChatDisplay = 1,
            Repeat = {5, 10, },
        },
        [1011] = { 
            ID = 1011,
            MessageType = 1,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "服务器%d时%d分钟更新，会断开连接数秒，请不要进行副本类活动！",
            Notice = 1,
            FriendChatDisplay = 1,
            Repeat = {5, 30, },
        },
        [1012] = { 
            ID = 1012,
            MessageType = 1,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，竞技场<color=#ff1919> 群雄逐鹿</color>玩法已经开启，奖励丰厚，玩法刺激，快去参加。",
            Notice = 1,
            FriendChatDisplay = 1,
            Repeat = {5, 30, },
        },
        [1013] = { 
            ID = 1013,
            MessageType = 1,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "服务器即将更新，会断开连接数秒，请注意！",
            Notice = 1,
            FriendChatDisplay = 1,
            Repeat = {},
        },
        [1014] = { 
            ID = 1014,
            MessageType = 1,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "服务器更新完成，感谢支持！",
            Notice = 1,
            FriendChatDisplay = 1,
            Repeat = {5, 30, },
        },
        [2001] = { 
            ID = 2001,
            MessageType = 3,
            Name = 0,
            Name1 = "战斗消息",
            TextContent = 0,
            TextContent1 = "你刚刚获得了props",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2002] = { 
            ID = 2002,
            MessageType = 2,
            Name = 0,
            Name1 = "战斗消息",
            TextContent = 0,
            TextContent1 = "你被蚩尤战神击败了",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2003] = { 
            ID = 2003,
            MessageType = 10,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "恭喜%s首次登顶%s",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2004] = { 
            ID = 2004,
            MessageType = 10,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "风云变色，%s夺得全服第%s",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2005] = { 
            ID = 2005,
            MessageType = 10,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "恭喜%s首次进入全服前10，",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2006] = { 
            ID = 2006,
            MessageType = 2,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "战斗获得%s点经验",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2007] = { 
            ID = 2007,
            MessageType = 2,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "满足条件%s,%s增加%s点怒气（满足条件1，祝融增加20点怒气）",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2008] = { 
            ID = 2008,
            MessageType = 2,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "掠夺玩家<color=#ff1919> %s</color> 群雄逐鹿积分<color=#469a18>%d</color>",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2009] = { 
            ID = 2009,
            MessageType = 2,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "被玩家<color=#ff1919> %s</color>掠夺群雄逐鹿积分<color=#469a18>%d</color>",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2010] = { 
            ID = 2010,
            MessageType = 2,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "获得群雄逐鹿积分<color=#469a18>%d</color>",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2011] = { 
            ID = 2011,
            MessageType = 3,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "玩家<color=#ff1919> %s</color>（需求）<color=#efdb00> %d点</color>：props",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2012] = { 
            ID = 2012,
            MessageType = 3,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "玩家<color=#ff1919> %s</color>（放弃）：props",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2013] = { 
            ID = 2013,
            MessageType = 2,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "获得功勋<color=#469a18>%d</color>",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2014] = { 
            ID = 2014,
            MessageType = 2,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "今日杀怪经验已达上限，杀怪不再获得",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [2015] = { 
            ID = 2015,
            MessageType = 2,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "获得威望<color=#469a18>%d</color>",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [3001] = { 
            ID = 3001,
            MessageType = 5,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "击杀%s获得%s点战功",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [3002] = { 
            ID = 3002,
            MessageType = 5,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "助攻击杀%s获得%s点战功",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [3003] = { 
            ID = 3003,
            MessageType = 5,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "%s：我当前血量已经低于百分之30，请%s的战士们能前往支援保护我。",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [3004] = { 
            ID = 3004,
            MessageType = 5,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "阵营boss%s不幸被击杀，请战士们打起精神，奋战到底。",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [3005] = { 
            ID = 3005,
            MessageType = 5,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "%s与同伴齐心协力，成功击杀阵营boss%s。为阵营获得100点攻防积分。",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [3006] = { 
            ID = 3006,
            MessageType = 5,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "物资车：%s的物资车正在被敌军拦截，请前往<u>%s</u>保护。",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [3007] = { 
            ID = 3007,
            MessageType = 5,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "%s物资车成功抵达，为阵营获得10点攻防积分。",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [3008] = { 
            ID = 3008,
            MessageType = 5,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "大攻防半小时后即将开启，请大家做好准备。",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [4001] = { 
            ID = 4001,
            MessageType = 6,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "%s帮会由于资金不足，已破产，将于72小时解散。请补充帮会资金。",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [4002] = { 
            ID = 4002,
            MessageType = 6,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "%s帮会资金充足，已解除破产危机。",
            Notice = 0,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [4003] = { 
            ID = 4003,
            MessageType = 4,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，阵营官职报名已经开始，快去报名吧！",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {5, 30, },
        },
        [4004] = { 
            ID = 4004,
            MessageType = 4,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，阵营官职选举已经开始，快去投票吧！",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {5, 30, },
        },
        [4005] = { 
            ID = 4005,
            MessageType = 4,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，新的阵营领袖已经产生，快去【阵营】-【官职】面板查看吧！",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {5, 30, },
        },
        [4006] = { 
            ID = 4006,
            MessageType = 4,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "阵营的勇士们，%s%s已经开启阵营全体BUFF，快去上阵杀敌吧！",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [4007] = { 
            ID = 4007,
            MessageType = 4,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "阵营的勇士们，%s%s已经阵营商店打折，快去【功勋商店】抢购吧！",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [4008] = { 
            ID = 4008,
            MessageType = 4,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，%s%s已经发放了阵营俸禄，快去【阵营】-【基础】面板领取吧！",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {},
        },
        [4009] = { 
            ID = 4009,
            MessageType = 4,
            Name = 0,
            Name1 = "系统消息",
            TextContent = 0,
            TextContent1 = "%s的勇士们，%s%s正在召唤你们前去支援！<u><color=#469a18>点击传送前往~</color></u> ",
            Notice = 1,
            FriendChatDisplay = 0,
            Repeat = {},
        },
    },

    ["Mail"] = {
        --ID: int    ID
        --MessageType: int    邮件类型
        --MailName: int    邮件抬头
        --MailName1: string    邮件抬头
        --MailSender: int    邮件发送人
        --MailSender1: string    邮件发送人
        --TextContent: int    邮件内容
        --TextContent1: string    邮件内容
        --Reward1: list_int    奖励1
        --Reward2: list_int    奖励2
        --Reward3: list_int    奖励3
        --Reward4: list_int    奖励4
        --Reward5: list_int    奖励5
        [9001] = { 
            ID = 9001,
            MessageType = 2,
            MailName = 0,
            MailName1 = "交易行邮件",
            MailSender = 0,
            MailSender1 = "交易官",
            TextContent = 0,
            TextContent1 = "%s真厉害运气太好了！在%s中获得了props，实在令人羡慕！",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9002] = { 
            ID = 9002,
            MessageType = 1,
            MailName = 0,
            MailName1 = "系统消息",
            MailSender = 0,
            MailSender1 = "竞技场指挥官",
            TextContent = 0,
            TextContent1 = "为了获得更好的游戏体验，服务器将在2017年1月19日5点进行例行维护。请各位小伙伴及时下线以防数据丢失。",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9003] = { 
            ID = 9003,
            MessageType = 1,
            MailName = 0,
            MailName1 = "系统消息",
            MailSender = 0,
            MailSender1 = "通灵宝印开发组",
            TextContent = 0,
            TextContent1 = "为了获得更好的游戏体验，服务器将在2017年1月19日5点进行例行维护。请各位小伙伴及时下线以防数据丢失。",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9004] = { 
            ID = 9004,
            MessageType = 4,
            MailName = 0,
            MailName1 = "公会消息通知",
            MailSender = 0,
            MailSender1 = "公会会长%s",
            TextContent = 0,
            TextContent1 = "您已被%s公会会长踢出公会。",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9005] = { 
            ID = 9005,
            MessageType = 3,
            MailName = 0,
            MailName1 = "每日排名",
            MailSender = 0,
            MailSender1 = "竞技场指挥官",
            TextContent = 0,
            TextContent1 = "由于你今日竞技场的出色表现，截至21：00您的排名为%s，获得竞技场积分%d。竞技场指挥官授予你以下奖励。",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9006] = { 
            ID = 9006,
            MessageType = 3,
            MailName = 0,
            MailName1 = "每周排名",
            MailSender = 0,
            MailSender1 = "竞技场指挥官",
            TextContent = 0,
            TextContent1 = "由于你本周竞技场的出色表现，您的最终排名为%s名，竞技场指挥官授予你以下奖励。",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9007] = { 
            ID = 9007,
            MessageType = 3,
            MailName = 0,
            MailName1 = "名次变化",
            MailSender = 0,
            MailSender1 = "竞技场指挥官",
            TextContent = 0,
            TextContent1 = "你被%s击败，竞技场名次掉落至%s。",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9008] = { 
            ID = 9008,
            MessageType = 1,
            MailName = 0,
            MailName1 = "团购奖励",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "由于团购活动中，在您之后有%d个人购买%s，给予以下奖励，越早购买礼包越多哦~",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9009] = { 
            ID = 9009,
            MessageType = 1,
            MailName = 0,
            MailName1 = "背包空间不足",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "由于背包空间不足，多出部分奖励将以邮件形式发放",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9010] = { 
            ID = 9010,
            MessageType = 1,
            MailName = 0,
            MailName1 = "登录有礼",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，感谢您对《通灵宝印》的支持，我们会继续努力，把产品做好。这是您的登录礼包，请查收。",
            Reward1 = {1012, 200000, },
            Reward2 = {1002, 666, },
            Reward3 = {4018, 10, },
            Reward4 = {},
            Reward5 = {},
        },
        [9011] = { 
            ID = 9011,
            MessageType = 1,
            MailName = 0,
            MailName1 = "登录有礼",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，感谢您对《通灵宝印》的支持，我们会继续努力，把产品做好。这是您的登录礼包，请查收。",
            Reward1 = {1012, 200000, },
            Reward2 = {1002, 666, },
            Reward3 = {4112, 10, },
            Reward4 = {},
            Reward5 = {},
        },
        [9012] = { 
            ID = 9012,
            MessageType = 1,
            MailName = 0,
            MailName1 = "登录有礼",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，感谢您对《通灵宝印》的支持，我们会继续努力，把产品做好。这是您的登录礼包，请查收。",
            Reward1 = {1012, 200000, },
            Reward2 = {1002, 666, },
            Reward3 = {4150, 1, },
            Reward4 = {},
            Reward5 = {},
        },
        [9013] = { 
            ID = 9013,
            MessageType = 1,
            MailName = 0,
            MailName1 = "登录有礼",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，感谢您对《通灵宝印》的支持，我们会继续努力，把产品做好。这是您的登录礼包，请查收。",
            Reward1 = {1012, 200000, },
            Reward2 = {1002, 666, },
            Reward3 = {4035, 10, },
            Reward4 = {},
            Reward5 = {},
        },
        [9014] = { 
            ID = 9014,
            MessageType = 1,
            MailName = 0,
            MailName1 = "登录有礼",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，感谢您对《通灵宝印》的支持，我们会继续努力，把产品做好。这是您的登录礼包，请查收。",
            Reward1 = {1012, 200000, },
            Reward2 = {1002, 888, },
            Reward3 = {5057, 10, },
            Reward4 = {},
            Reward5 = {},
        },
        [9015] = { 
            ID = 9015,
            MessageType = 1,
            MailName = 0,
            MailName1 = "登录有礼",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，感谢您对《通灵宝印》的支持，我们会继续努力，把产品做好。这是您的登录礼包，请查收。",
            Reward1 = {1012, 200000, },
            Reward2 = {1002, 888, },
            Reward3 = {4027, 5, },
            Reward4 = {},
            Reward5 = {},
        },
        [9016] = { 
            ID = 9016,
            MessageType = 1,
            MailName = 0,
            MailName1 = "登录有礼",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，感谢您对《通灵宝印》的支持，我们会继续努力，把产品做好。这是您的登录礼包，请查收。",
            Reward1 = {1012, 200000, },
            Reward2 = {1002, 888, },
            Reward3 = {5059, 1, },
            Reward4 = {},
            Reward5 = {},
        },
        [9017] = { 
            ID = 9017,
            MessageType = 1,
            MailName = 0,
            MailName1 = "登录有礼",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，感谢您对《通灵宝印》的支持，我们会继续努力，把产品做好。这是您的登录礼包，请查收。",
            Reward1 = {1012, 500000, },
            Reward2 = {1002, 1666, },
            Reward3 = {4083, 5, },
            Reward4 = {},
            Reward5 = {},
        },
        [9018] = { 
            ID = 9018,
            MessageType = 1,
            MailName = 0,
            MailName1 = "一骑绝尘",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“一骑绝尘”，活动中的优秀表现，特奖励您“一骑绝尘”礼包一个，请查收。",
            Reward1 = {1012, 1000000, },
            Reward2 = {4025, 20, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9019] = { 
            ID = 9019,
            MessageType = 1,
            MailName = 0,
            MailName1 = "一骑绝尘",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“一骑绝尘”，活动中的优秀表现，特奖励您“一骑绝尘”礼包一个，请查收。",
            Reward1 = {1012, 900000, },
            Reward2 = {4024, 20, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9020] = { 
            ID = 9020,
            MessageType = 1,
            MailName = 0,
            MailName1 = "一骑绝尘",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“一骑绝尘”，活动中的优秀表现，特奖励您“一骑绝尘”礼包一个，请查收。",
            Reward1 = {1012, 800000, },
            Reward2 = {4023, 20, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9021] = { 
            ID = 9021,
            MessageType = 1,
            MailName = 0,
            MailName1 = "魅力四射",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“魅力四射”活动中的优秀表现，特奖励您“魅力四射”礼包一个，请查收。",
            Reward1 = {1002, 2000, },
            Reward2 = {5074, 1, },
            Reward3 = {5075, 1, },
            Reward4 = {},
            Reward5 = {},
        },
        [9022] = { 
            ID = 9022,
            MessageType = 1,
            MailName = 0,
            MailName1 = "魅力四射",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“魅力四射”活动中的优秀表现，特奖励您“魅力四射”礼包一个，请查收。",
            Reward1 = {1002, 1500, },
            Reward2 = {5074, 1, },
            Reward3 = {5075, 1, },
            Reward4 = {},
            Reward5 = {},
        },
        [9023] = { 
            ID = 9023,
            MessageType = 1,
            MailName = 0,
            MailName1 = "魅力四射",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“魅力四射”活动中的优秀表现，特奖励您“魅力四射”礼包一个，请查收。",
            Reward1 = {1002, 1000, },
            Reward2 = {5074, 1, },
            Reward3 = {5075, 1, },
            Reward4 = {},
            Reward5 = {},
        },
        [9024] = { 
            ID = 9024,
            MessageType = 1,
            MailName = 0,
            MailName1 = "魅力四射",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“魅力四射”活动中的优秀表现，特奖励您“魅力四射”礼包一个，请查收。",
            Reward1 = {1002, 2000, },
            Reward2 = {5075, 1, },
            Reward3 = {5074, 1, },
            Reward4 = {},
            Reward5 = {},
        },
        [9025] = { 
            ID = 9025,
            MessageType = 1,
            MailName = 0,
            MailName1 = "魅力四射",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“魅力四射”活动中的优秀表现，特奖励您“魅力四射”礼包一个，请查收。",
            Reward1 = {1002, 1500, },
            Reward2 = {5075, 1, },
            Reward3 = {5074, 1, },
            Reward4 = {},
            Reward5 = {},
        },
        [9026] = { 
            ID = 9026,
            MessageType = 1,
            MailName = 0,
            MailName1 = "魅力四射",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“魅力四射”活动中的优秀表现，特奖励您“魅力四射”礼包一个，请查收。",
            Reward1 = {1002, 1000, },
            Reward2 = {5075, 1, },
            Reward3 = {5074, 1, },
            Reward4 = {},
            Reward5 = {},
        },
        [9027] = { 
            ID = 9027,
            MessageType = 1,
            MailName = 0,
            MailName1 = "花丛圣手",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“花丛圣手”活动中的优秀表现，特奖励您“花丛圣手”礼包一个，请查收。",
            Reward1 = {5059, 10, },
            Reward2 = {4083, 10, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9028] = { 
            ID = 9028,
            MessageType = 1,
            MailName = 0,
            MailName1 = "花丛圣手",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“花丛圣手”活动中的优秀表现，特奖励您“花丛圣手”礼包一个，请查收。",
            Reward1 = {5059, 5, },
            Reward2 = {4083, 8, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9029] = { 
            ID = 9029,
            MessageType = 1,
            MailName = 0,
            MailName1 = "花丛圣手",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“花丛圣手”活动中的优秀表现，特奖励您“花丛圣手”礼包一个，请查收。",
            Reward1 = {5058, 10, },
            Reward2 = {4083, 6, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9030] = { 
            ID = 9030,
            MessageType = 1,
            MailName = 0,
            MailName1 = "武林至尊",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“武林至尊”活动中的优秀表现，特奖励您“武林至尊”礼包一个，请查收。",
            Reward1 = {4027, 5, },
            Reward2 = {5076, 1, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9031] = { 
            ID = 9031,
            MessageType = 1,
            MailName = 0,
            MailName1 = "武林至尊",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“武林至尊”活动中的优秀表现，特奖励您“武林至尊”礼包一个，请查收。",
            Reward1 = {4027, 4, },
            Reward2 = {5076, 1, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9032] = { 
            ID = 9032,
            MessageType = 1,
            MailName = 0,
            MailName1 = "武林至尊",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“武林至尊”活动中的优秀表现，特奖励您“武林至尊”礼包一个，请查收。",
            Reward1 = {4027, 3, },
            Reward2 = {5076, 1, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9033] = { 
            ID = 9033,
            MessageType = 1,
            MailName = 0,
            MailName1 = "睥睨群雄",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“睥睨群雄”活动中的优秀表现，特奖励您“睥睨群雄”礼包一个，请查收。",
            Reward1 = {1002, 3888, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9034] = { 
            ID = 9034,
            MessageType = 1,
            MailName = 0,
            MailName1 = "睥睨群雄",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“睥睨群雄”活动中的优秀表现，特奖励您“睥睨群雄”礼包一个，请查收。",
            Reward1 = {1002, 2888, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9035] = { 
            ID = 9035,
            MessageType = 1,
            MailName = 0,
            MailName1 = "睥睨群雄",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“睥睨群雄”活动中的优秀表现，特奖励您“睥睨群雄”礼包一个，请查收。",
            Reward1 = {1002, 2666, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9036] = { 
            ID = 9036,
            MessageType = 1,
            MailName = 0,
            MailName1 = "战意冲天",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“战意冲天”活动中的优秀表现，特奖励您“战意冲天”礼包一个，请查收。",
            Reward1 = {1012, 4000000, },
            Reward2 = {5077, 1, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9037] = { 
            ID = 9037,
            MessageType = 1,
            MailName = 0,
            MailName1 = "战意冲天",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“战意冲天”活动中的优秀表现，特奖励您“战意冲天”礼包一个，请查收。",
            Reward1 = {1012, 3500000, },
            Reward2 = {5077, 1, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9038] = { 
            ID = 9038,
            MessageType = 1,
            MailName = 0,
            MailName1 = "战意冲天",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“战意冲天”活动中的优秀表现，特奖励您“战意冲天”礼包一个，请查收。",
            Reward1 = {1012, 3200000, },
            Reward2 = {5077, 1, },
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9039] = { 
            ID = 9039,
            MessageType = 1,
            MailName = 0,
            MailName1 = "战力十足",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“战力十足”活动中的优秀表现，特奖励您“战力十足”礼包一个，请查收。",
            Reward1 = {1012, 2000000, },
            Reward2 = {4025, 50, },
            Reward3 = {5060, 5, },
            Reward4 = {},
            Reward5 = {},
        },
        [9040] = { 
            ID = 9040,
            MessageType = 1,
            MailName = 0,
            MailName1 = "战力十足",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“战力十足”活动中的优秀表现，特奖励您“战力十足”礼包一个，请查收。",
            Reward1 = {1012, 2000000, },
            Reward2 = {4025, 45, },
            Reward3 = {5060, 4, },
            Reward4 = {},
            Reward5 = {},
        },
        [9041] = { 
            ID = 9041,
            MessageType = 1,
            MailName = 0,
            MailName1 = "战力十足",
            MailSender = 0,
            MailSender1 = "通灵宝印官方运营团队",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为奖励您在“战力十足”活动中的优秀表现，特奖励您“战力十足”礼包一个，请查收。",
            Reward1 = {1012, 2000000, },
            Reward2 = {4025, 40, },
            Reward3 = {5060, 3, },
            Reward4 = {},
            Reward5 = {},
        },
        [9042] = { 
            ID = 9042,
            MessageType = 5,
            MailName = 0,
            MailName1 = "战功排名",
            MailSender = 0,
            MailSender1 = "阵营首领",
            TextContent = 0,
            TextContent1 = "由于你今日大攻防的出色表现，战功排名%d，获得如下奖励，请查收。",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9043] = { 
            ID = 9043,
            MessageType = 1,
            MailName = 0,
            MailName1 = "恭喜你当选阵营官员",
            MailSender = 0,
            MailSender1 = "阵营首领",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，恭喜你在阵营选举中脱颖而出，当选%s一职。请珍惜阵营玩家对你的信任，带领全阵营走向强盛。",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9100] = { 
            ID = 9100,
            MessageType = 1,
            MailName = 0,
            MailName1 = "组队副本霸主奖励",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，由于你英勇的表现，恭喜你获得%s组队副本的副本霸主，特奖励副本霸主礼包一个，请查收。",
            Reward1 = {5003, 1, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9101] = { 
            ID = 9101,
            MessageType = 1,
            MailName = 0,
            MailName1 = "组队副本霸主榜第一名奖励",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为表彰你%s组队副本霸主榜第一名的尊贵身份，特奖励你以下霸主积分，请查收。",
            Reward1 = {1007, 50, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9102] = { 
            ID = 9102,
            MessageType = 1,
            MailName = 0,
            MailName1 = "组队副本霸主榜第二名奖励",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为表彰你%s组队副本霸主榜第二名的尊贵身份，特奖励你以下霸主积分，请查收。",
            Reward1 = {1007, 40, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9103] = { 
            ID = 9103,
            MessageType = 1,
            MailName = 0,
            MailName1 = "组队副本霸主榜第三名奖励",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为表彰你%s组队副本霸主榜第三名的尊贵身份，特奖励你以下霸主积分，请查收。",
            Reward1 = {1007, 30, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9104] = { 
            ID = 9104,
            MessageType = 1,
            MailName = 0,
            MailName1 = "主线副本副本霸主奖励",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，由于你英勇的表现，恭喜你获得%s副本的副本霸主，特奖励副本霸主礼包一个，请查收。",
            Reward1 = {5003, 1, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9105] = { 
            ID = 9105,
            MessageType = 1,
            MailName = 0,
            MailName1 = "主线副本霸主榜第一名奖励",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为表彰你%s主线副本霸主榜第一名的尊贵身份，特奖励你以下霸主积分，请查收。",
            Reward1 = {1007, 50, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9106] = { 
            ID = 9106,
            MessageType = 1,
            MailName = 0,
            MailName1 = "主线副本霸主榜第二名奖励",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为表彰你%s主线副本霸主榜第二名的尊贵身份，特奖励你以下霸主积分，请查收。",
            Reward1 = {1007, 40, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9107] = { 
            ID = 9107,
            MessageType = 1,
            MailName = 0,
            MailName1 = "主线副本霸主榜第三名奖励",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为表彰你%s主线副本霸主榜第三名的尊贵身份，特奖励你以下霸主积分，请查收。",
            Reward1 = {1007, 30, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9108] = { 
            ID = 9108,
            MessageType = 1,
            MailName = 0,
            MailName1 = "主线副本霸主榜第四名奖励",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为表彰你%s主线副本霸主榜第四名的尊贵身份，特奖励你以下霸主积分，请查收。",
            Reward1 = {1007, 20, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9109] = { 
            ID = 9109,
            MessageType = 1,
            MailName = 0,
            MailName1 = "主线副本霸主榜第五名奖励",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，为表彰你%s主线副本霸主榜第五名的尊贵身份，特奖励你以下霸主积分，请查收。",
            Reward1 = {1007, 10, },
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
        [9110] = { 
            ID = 9110,
            MessageType = 1,
            MailName = 0,
            MailName1 = "霸主礼包获取次数达到上限",
            MailSender = 0,
            MailSender1 = "系统",
            TextContent = 0,
            TextContent1 = "亲爱的玩家，您本日获取%s副本的霸主礼包次数已经达到上限，无法继续获取。",
            Reward1 = {},
            Reward2 = {},
            Reward3 = {},
            Reward4 = {},
            Reward5 = {},
        },
    },

    ["ChannelControl"] = {
        --MessageType: int    消息类型
        --Color: string    色值
        --FactionChat: int    阵营频道
        --TeamChat: int    队伍
        --UnionChat: int    公会
        --SystemMessage: int    系统
        --MainMessage: int    主界面
        --Loudspeaker: int    喇叭
        --NearbyChat: int    附近
        [1] = { 
            MessageType = 1,
            Color = "#f39d50",
            FactionChat = 1,
            TeamChat = 1,
            UnionChat = 1,
            SystemMessage = 1,
            MainMessage = 1,
            Loudspeaker = 1,
            NearbyChat = 1,
        },
        [2] = { 
            MessageType = 2,
            Color = "#f39d51",
            FactionChat = 0,
            TeamChat = 0,
            UnionChat = 0,
            SystemMessage = 1,
            MainMessage = 0,
            Loudspeaker = 0,
            NearbyChat = 0,
        },
        [3] = { 
            MessageType = 3,
            Color = "#f39d52",
            FactionChat = 0,
            TeamChat = 0,
            UnionChat = 0,
            SystemMessage = 1,
            MainMessage = 1,
            Loudspeaker = 0,
            NearbyChat = 0,
        },
        [4] = { 
            MessageType = 4,
            Color = "#f39d53",
            FactionChat = 1,
            TeamChat = 1,
            UnionChat = 1,
            SystemMessage = 1,
            MainMessage = 1,
            Loudspeaker = 1,
            NearbyChat = 1,
        },
        [5] = { 
            MessageType = 5,
            Color = "#dfccbd",
            FactionChat = 1,
            TeamChat = 0,
            UnionChat = 0,
            SystemMessage = 0,
            MainMessage = 1,
            Loudspeaker = 0,
            NearbyChat = 0,
        },
        [6] = { 
            MessageType = 6,
            Color = "#dda660",
            FactionChat = 0,
            TeamChat = 0,
            UnionChat = 1,
            SystemMessage = 0,
            MainMessage = 1,
            Loudspeaker = 0,
            NearbyChat = 0,
        },
        [7] = { 
            MessageType = 7,
            Color = "#55892d",
            FactionChat = 0,
            TeamChat = 1,
            UnionChat = 0,
            SystemMessage = 0,
            MainMessage = 1,
            Loudspeaker = 0,
            NearbyChat = 0,
        },
        [8] = { 
            MessageType = 8,
            Color = "#8bc070",
            FactionChat = 0,
            TeamChat = 0,
            UnionChat = 0,
            SystemMessage = 0,
            MainMessage = 1,
            Loudspeaker = 0,
            NearbyChat = 1,
        },
        [9] = { 
            MessageType = 9,
            Color = "#f39d50",
            FactionChat = 1,
            TeamChat = 1,
            UnionChat = 1,
            SystemMessage = 0,
            MainMessage = 1,
            Loudspeaker = 1,
            NearbyChat = 1,
        },
        [10] = { 
            MessageType = 10,
            Color = "#f39d54",
            FactionChat = 0,
            TeamChat = 0,
            UnionChat = 1,
            SystemMessage = 1,
            MainMessage = 0,
            Loudspeaker = 0,
            NearbyChat = 0,
        },
    },

    ["Parameter"] = {
        --ID: int    参数ID
        --Value: float    值
        --Introduction: string    说明
        [1] = { 
            ID = 1,
            Value = 5.0,
            Introduction = "在公告消息列表只有一条消息时，该喇叭消息会存在5秒。",
        },
        [2] = { 
            ID = 2,
            Value = 100.0,
            Introduction = "好友上限",
        },
        [3] = { 
            ID = 3,
            Value = 100.0,
            Introduction = "最近消息上限",
        },
        [4] = { 
            ID = 4,
            Value = 100.0,
            Introduction = "黑名单上限",
        },
        [5] = { 
            ID = 5,
            Value = 100.0,
            Introduction = "仇人上限",
        },
        [6] = { 
            ID = 6,
            Value = 5.0,
            Introduction = "好友搜索CD",
        },
        [7] = { 
            ID = 7,
            Value = 1.0,
            Introduction = "玩家与好友每进行一次组队任务时，增加X点好友度",
        },
        [8] = { 
            ID = 8,
            Value = 1.0,
            Introduction = "玩家与好友进行刷怪时，每15分钟增加X点好友度",
        },
        [9] = { 
            ID = 9,
            Value = 99.0,
            Introduction = "好友度高于该值时，需要使用道具提升",
        },
        [10] = { 
            ID = 10,
            Value = 1.0,
            Introduction = "玩家被好友击杀时，好友度将降低至1点",
        },
        [11] = { 
            ID = 11,
            Value = 1.0,
            Introduction = "玩家主动将其他玩家或好友加入黑名单或仇人名单时，好友度都将降至1点",
        },
        [12] = { 
            ID = 12,
            Value = 120.0,
            Introduction = "文字聊天最长字符",
        },
        [13] = { 
            ID = 13,
            Value = 20.0,
            Introduction = "好友申请列表人数上限",
        },
        [14] = { 
            ID = 14,
            Value = 10.0,
            Introduction = "附近范围：附近频道的消息范围，以玩家为中心的半径",
        },
        [15] = { 
            ID = 15,
            Value = 3.0,
            Introduction = "聊天泡泡存在时间",
        },
        [16] = { 
            ID = 16,
            Value = 50.0,
            Introduction = "邮件显示数量上限",
        },
        [17] = { 
            ID = 17,
            Value = 30.0,
            Introduction = "邮件保存天数",
        },
        [18] = { 
            ID = 18,
            Value = 9999.0,
            Introduction = "好友度上限",
        },
    },

    ["Friendly"] = {
        --Friendly: int    好友度
        --Title: string    称号
        [1] = { 
            Friendly = 1111,
            Title = "普通好友",
        },
        [2] = { 
            Friendly = 2222,
            Title = "亲密好友",
        },
        [3] = { 
            Friendly = 3333,
            Title = "挚交好友",
        },
        [4] = { 
            Friendly = 4444,
            Title = "患难之交",
        },
        [5] = { 
            Friendly = 5555,
            Title = "生死之交",
        },
    },

}
